from rsf.tex import *

End(

options='georeport,12pt',

use='natbib,graphicx,color,amsmath,amsthm,amssymb,amsbsy,wasysym,setspace,bm,float,hyperref,algorithm,algpseudocode',

include=r'''
\newcommand{\mb}{\mathbf}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\bk}{\mathbf{k}}
\newcommand{\bv}{\mathbf{v}}
\newcommand{\bu}{\mathbf{u}}
\newcommand{\by}{\mathbf{y}}
\newcommand{\bz}{\mathbf{z}}
\newcommand{\bg}{\mathbf{g}}
\newcommand{\bh}{\mathbf{h}}
\newcommand{\bR}{\mathbf{R}}
\newcommand{\oS}{\bar{S}}
\newcommand{\of}{\bar{f}}
\newcommand{\ofa}{\bar{f}_{\alpha,\lambda}}
\newcommand{\oNa}{\bar{N}_{\alpha,\lambda}}
\newcommand{\Ja}{J_{\alpha,\lambda}}
\newcommand{\Jared}{\tilde{J}_{\alpha,\lambda}}
\newcommand{\Ml}{M + \lambda^2I}
\newcommand{\Mld}{M_{\lambda}^{\dagger}}
\newtheorem{lemma}{Lemma}
\newtheorem{theorem}{Theorem}
\newtheorem{alg}{Algorithm}
\newtheorem{remark}{Remark}
\newtheorem{cor}{Corollary}
\newtheorem{example}{Example}
\newtheorem{definition}{Defenition}

''',
color='ALL'
)





