from rsf.proj import *

import os
import scenv

RSFROOT         = os.getenv('RSFROOT')
sfcp            = os.path.join(RSFROOT,'bin/sfcp')

MYAPPS          = os.getenv("MYAPPS")
python          = os.path.join(MYAPPS,'conda/miniconda/bin/python')

BASIC='../data'

# build dict of data to import
dd = dict(DATA='d11.su', SDATA='sd11.su', FILT='u11.su', SRC='w11.su', HOM='m0.rsf', BUOY='bym.rsf', COV='cx.rsf')

# retrieve data
if not os.path.exists(BASIC):
    print('cannot find data source directory ' + BASIC)
    Exit(1)
else:
    for it in dd.keys():
        ITEM = os.path.join(BASIC,dd[it])
        if not os.path.exists(ITEM):
            print('you must build the target ' + ITEM)
            print('before building this project') 
            Exit(1)
        Flow(dd[it],ITEM,'/bin/cp ' + ITEM + ' ' + dd[it], stdin=0, stdout=-1)

# set up MSWI parameters
fdpars = 'order=2 sampord=1 nsnaps=20 cfl=0.5 cmin=1.0 cmax=3.0 dmin=0.8 dmax=3.0' + \
        ' ' + 'nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0 boundstest=True noisy=True partask=3'

smpars = 'rect1=10 rect2=10 repeat=2'

mswipars = 'alpha=0.0001 sigma=0.00001 rho=0.0025 kmax=1000 verbose=2'

lspars = 'lsmax=10 mured=0.5 muinc=1.8 gammared=0.1 gammainc=0.9'

# 11 shot at m0 - produce filter at homog model
descpars0 = r'descmax=0 desceps=0.01 descverbose=1 descout=\'outfile0.txt\' lsverbose=1'
pars = ' ' + fdpars + ' ' + smpars + ' ' + mswipars + ' ' + descpars0 + ' ' + lspars

Flow(['mest0.rsf', 'uest0.su'],
     [dd['HOM'], dd['DATA'] , dd['FILT'], dd['SRC'], dd['BUOY']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u msmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars, stdin=0, stdout=-1)

Flow(['smest0.rsf', 'suest0.su'],
     [dd['HOM'], dd['SDATA'] , dd['FILT'], dd['SRC'], dd['BUOY']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u msmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars, stdin=0, stdout=-1)
     
# 11 shot MSWI
#descpars = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfile11.txt\' lsverbose=1'
descpars = r'descmax=12 desceps=0.01 descverbose=1 lsverbose=1'
pars = ' ' + fdpars + ' ' + smpars + ' ' + mswipars + ' ' + descpars + ' ' + lspars

Flow(['mest11.rsf', 'uest11.su'],
     [dd['HOM'], dd['DATA'], dd['FILT'], dd['SRC'], dd['BUOY']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u msmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars, stdin=0, stdout=-1)

# 11 shot MSWI with CofV
descpars_cov = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfile11cov.txt\' lsverbose=1'
pars_cov = ' ' + fdpars + ' ' + smpars + ' ' + mswipars + ' ' + descpars_cov + ' ' + lspars

Flow(['cmest11.rsf', 'cuest11.su'],
     [dd['HOM'], dd['DATA'], dd['FILT'], dd['SRC'], dd['BUOY'], dd['COV']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u modmsmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' cmodin=\'${SOURCES[4]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars_cov, stdin=0, stdout=-1)

# 11 show MSWI with alpha update, starting at alpha=0

mswipars_aup0 = 'alpha=0.0 sigma=0.00001 rho=0.0025 kmax=1000 verbose=2 etar=0.02 ratminus=0.75 ratplus=1.25'
descpars_aup0 = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfile11aup.txt\' lsverbose=1'
pars_aup0 = ' ' + fdpars + ' ' + smpars + ' ' + mswipars_aup0 + ' ' + descpars_aup0 + ' ' + lspars

Flow(['mest11aup0.rsf', 'uest11aup0.su'],
     [dd['HOM'], dd['DATA'], dd['FILT'], dd['SRC'], dd['BUOY']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u msmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars_aup0, stdin=0, stdout=-1)

# FWI from final 11shot MSWI estimate
descparsfwi = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfilefwi.txt\' lsverbose=1'
fwipars = ' ' + fdpars + ' ' + smpars + ' ' + descparsfwi + ' ' + lspars

Flow('mestfwi.rsf',
    ['mest11.rsf', dd['DATA'], dd['SRC'], dd['BUOY']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' -u fwi.py bulkmodout=\'${TARGETS[0]}\'' + \
     	      r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\'' + \
              r' buoyancy=\'${SOURCES[3]}\' source=\'${SOURCES[2]}\'' + \
	      fwipars, stdin=0, stdout=-1)

Flow('resimfwi.su',[dd['DATA'], dd['SRC'], 'mestfwi.rsf', dd['BUOY']],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)

# FWI from homogeneous bulk mod
descparsfwi0 = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfilefwi0.txt\' lsverbose=1'
fwi0pars = ' ' + fdpars + ' ' + smpars + ' ' + descparsfwi0 + ' ' + lspars

Flow('mestfwi0.rsf',
    [dd['HOM'], dd['DATA'], dd['SRC'], dd['BUOY']],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' -u fwi.py bulkmodout=\'${TARGETS[0]}\'' + \
     	      r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\'' + \
              r' buoyancy=\'${SOURCES[3]}\' source=\'${SOURCES[2]}\'' + \
	      fwipars, stdin=0, stdout=-1)

Flow('resimfwi0.su',[dd['DATA'], dd['SRC'], 'mestfwi0.rsf',dd['BUOY']],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)

Flow('sim0.su',[dd['DATA'], dd['SRC'], dd['HOM'], dd['BUOY']],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)

Flow('sim11.su',[dd['DATA'], dd['SRC'], 'mest11.rsf', dd['BUOY']],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)