#############################################################################
###################### COMMON DEFINITIONS - DO NOT ALTER ####################
#############################################################################
from rsf.proj import *
import os

#############################################################################
###################### END COMMON DEFINITIONS ###############################
#############################################################################

######################## LOCAL DEFINITIONS ##################################
######## abbreviations for commands used in flows - put these first, if
######## you use abbreviations
# example:
#          CWPROOT         = os.getenv('CWPROOT')
#          ...
#          sunull          = os.path.join(CWPROOT,'bin/sunull')
CWPROOT         = os.getenv('CWPROOT')
segyread        = os.path.join(CWPROOT,'bin/segyread')
suwind          = os.path.join(CWPROOT,'bin/suwind')
susort          = os.path.join(CWPROOT,'bin/susort')
sumute          = os.path.join(CWPROOT,'bin/sumute')
sufilter        = os.path.join(CWPROOT,'bin/sufilter')
suvelan         = os.path.join(CWPROOT,'bin/suvelan')
sunmo           = os.path.join(CWPROOT,'bin/sunmo')
sustack         = os.path.join(CWPROOT,'bin/sustack')
sugain          = os.path.join(CWPROOT,'bin/sugain')
sugazmig        = os.path.join(CWPROOT,'bin/sugazmig')
velconv         = os.path.join(CWPROOT,'bin/velconv')
smooth2         = os.path.join(CWPROOT,'bin/smooth2')
unisam2         = os.path.join(CWPROOT,'bin/unisam2')
transp          = os.path.join(CWPROOT,'bin/transp')
sumigpspi       = os.path.join(CWPROOT,'bin/sumigpspi')
sumigfd         = os.path.join(CWPROOT,'bin/sumigfd')
sufilter        = os.path.join(CWPROOT,'bin/sufilter')
sufft           = os.path.join(CWPROOT,'bin/sufft')
suamp           = os.path.join(CWPROOT,'bin/suamp')
suspike         = os.path.join(CWPROOT,'bin/suspike')
suplane         = os.path.join(CWPROOT,'bin/suplane')
sushw           = os.path.join(CWPROOT,'bin/sushw')
suchw           = os.path.join(CWPROOT,'bin/suchw')
suop2           = os.path.join(CWPROOT,'bin/suop2')
MYAPPS          = os.getenv('MYAPPS')
asg             = os.path.join(MYAPPS,'trip/iwave/asg/main/asg.x')
asglin          = os.path.join(MYAPPS,'trip/iwave/asg/main/asglin.x')
explref         = os.path.join(MYAPPS,'trip/iwave/asg/main/explref.x')
towed_array     = os.path.join(MYAPPS,'trip/iwave/trace/main/towed_array.x')

# files from basic: bp05103040.su, paracdpf.su, paravintz.rsf
# zero phase bandpass filter a la Jie
# stack masquerading as zero-offset data
PSDATA = 'paracdp.su'
DATA = 'parastackf.su'	
VELO = 'paravintz.rsf'
VBIN = 'paravintz.bin'
IMAGE= 'parapspif.rsf'
BASIC='../../basic/project' 

if not os.path.exists(BASIC):
   print 'you must install basic on the same level as'
   print 'the parent directory (born) to build this project'
   Exit(1)
else:
   for i in [PSDATA, DATA, VELO, VBIN, IMAGE]:
       SRC = os.path.join(BASIC,i)
       if not os.path.exists(SRC):
           print 'you must build the target ' + SRC
	   print 'before building this project'	
	   Exit(1)
       Flow(i,SRC,'/bin/cp ' + SRC + ' ' + i, stdin=0, stdout=-1)
	  
#       if os.path.exists(SRC):	
#       	  Flow(i,None,'/bin/rm -rf ' + i + '; ln -s ' + SRC + ' .',stdin=0,stdout=-1)
#       else:
#          Flow(i,None,
#	       'cd ' + BASIC + '; export CWPROOT=' + CWPROOT + '; ' + 
#	       myscons + ' ' + i + '; cd ' + 
#	       thispath + '; /bin/rm -rf ' + i + '; ln -s ' + SRC + ' .',stdin=0,stdout=-1)

# clean up stack - remove redundant traces, compute midpoint and assign to gx,
# set sx=0 so it's treated as one shot
Flow('parastackfix.su','parastackf.su',
     suchw + ' key1=gx,sx key2=gx,sx key3=sx,sx ' + 
     ' a=0,0 b=0.5,0 c=0.5,0')

# new pspi based on filtered data
Flow('parastackfixagc.su','parastackfix.su', sugain + ' agc=1')
Flow('parastackfixagcfilt.su','parastackfixagc.su',sufilter + ' f=2,5,20,25')

# Gazdag PSPI poststack depth migration
Flow('vtransp.bin','paravintz.bin',transp + ' n1=401')
Flow('parapspifixagcfilt.su', ['parastackfixagcfilt.su','vtransp.bin'], sumigpspi + ' vfile=${SOURCES[1]} nz=401 dz=10 dx=12.5 tmpdir=/var/tmp')
Flow('parapspifixagcfilt','parapspifixagcfilt.su','suread endian=0 read=data|put d1=10 unit1=m d2=12.5 unit2=m o2=1617.5')

# change units to m/ms = km/s in interval velocity 
Flow('paravintzmms', ['paravintz.rsf','paravintz.bin'], 'add scale=0.001')

# square to form bulk mod - here rho=1 gm/cc all wet
Flow('paracsq','paravintzmms','add mode=p ${SOURCES[0]} |put data_type=bulk')
Flow('paracsqer','paracsq','add scale=0.25')

# unit buoyancy
Flow('unitbuoy','paracsq',
     'add scale=0.0 | add add=1.0')
     
# exploding reflector modeling
Flow(['expldata.su'],['paracsqer','unitbuoy','parapspifixagcfilt','parastackfixagcfilt.su'],
     sugain + ' scale=0.0 < ${SOURCES[3]} > ${TARGETS[0]} && ' +
     explref + ' CWPROOT=' + CWPROOT + ' ' +
     '''
     bulkmod=${SOURCES[0]} buoyancy=${SOURCES[1]} 
     explref=${SOURCES[2]} data=${TARGETS[0]}
     deriv=0 order=2 cfl=0.5 cmin=0.5 cmax=2.5 
     dmin=0.8 dmax=3.0 nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0
     dump_lda=1 dump_ldc=1 dump_term=1 sampord=1 adjtest1=1
     ''',stdin=0,stdout=-1,workdir='$TARGET.work')

# exploding reflector cg inv 1 it nmo bg
Flow(['explnmo1it'],['paracsqer','unitbuoy','parapspifixagcfilt','parastackfixagcfilt.su'],
     'add scale=0.0 < ${SOURCES[2]} > ${TARGETS[0]} && ' +
     explref + ' CWPROOT=' + CWPROOT + ' ' +
     '''
     bulkmod=${SOURCES[0]} buoyancy=${SOURCES[1]} 
     explref=${SOURCES[2]} explref_inv=${TARGETS[0]}
     data_p=${SOURCES[3]}
     order=2 cfl=0.5 cmin=0.5 cmax=2.5 
     dmin=0.8 dmax=3.0 nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0
     dump_lda=1 dump_ldc=1 dump_term=1 sampord=1 MaxIter=1 outfile="cgrec.txt"
     ''',stdin=0,stdout=-1,workdir='$TARGET.work')

# exploding reflector cg inv 6 it nmo bg
Flow(['explnmo6it'],['paracsqer','unitbuoy','parapspifixagcfilt','parastackfixagcfilt.su'],
     'add scale=0.0 < ${SOURCES[2]} > ${TARGETS[0]} && ' +
     explref + ' CWPROOT=' + CWPROOT + ' ' +
     '''
     bulkmod=${SOURCES[0]} buoyancy=${SOURCES[1]} 
     explref=${SOURCES[2]} explref_inv=${TARGETS[0]}
     data_p=${SOURCES[3]}
     order=2 cfl=0.5 cmin=0.5 cmax=2.5 
     dmin=0.8 dmax=3.0 nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0
     dump_lda=1 dump_ldc=1 dump_term=1 sampord=1 MaxIter=6 outfile="cgrec.txt"
     ''',stdin=0,stdout=-1,workdir='$TARGET.work')

# exploding reflector modeling, nmo v, refl from 1 its cg
Flow(['expldatanmo1it.su'],['paracsqer','unitbuoy','explnmo1it','parastackfixagcfilt.su'],
     sugain + ' scale=0.0 < ${SOURCES[3]} > ${TARGETS[0]} && ' +
     explref + ' CWPROOT=' + CWPROOT + ' ' +
     '''
     bulkmod=${SOURCES[0]} buoyancy=${SOURCES[1]} 
     explref=${SOURCES[2]} data_p=${TARGETS[0]}
     deriv=0 order=2 cfl=0.5 cmin=0.5 cmax=2.5 
     dmin=0.8 dmax=3.0 nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0
     dump_lda=1 dump_ldc=1 dump_term=1 sampord=1 
     ''',stdin=0,stdout=-1,workdir='$TARGET.work')

# exploding reflector modeling, nmo v, refl from 6 its cg
Flow(['expldatanmo6it.su'],['paracsqer','unitbuoy','explnmo6it','parastackfixagcfilt.su'],
     sugain + ' scale=0.0 < ${SOURCES[3]} > ${TARGETS[0]} && ' +
     explref + ' CWPROOT=' + CWPROOT + ' ' +
     '''
     bulkmod=${SOURCES[0]} buoyancy=${SOURCES[1]} 
     explref=${SOURCES[2]} data_p=${TARGETS[0]}
     deriv=0 order=2 cfl=0.5 cmin=0.5 cmax=2.5 
     dmin=0.8 dmax=3.0 nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0
     dump_lda=1 dump_ldc=1 dump_term=1 sampord=1 
     ''',stdin=0,stdout=-1,workdir='$TARGET.work')

# residual
Flow('resdatanmo6it.su',['expldatanmo6it.su','parastackfixagcfilt.su'],
     suop2 + ' ${SOURCES[0]} ${SOURCES[1]} op=diff', stdin=0)

# exploding reflector migration, nmo model
Flow(['reflnmo'],['paracsqer','unitbuoy','parapspifixagcfilt','parastackfixagcfilt.su'],
     'add scale=0.0 < ${SOURCES[2]} > ${TARGETS[0]} && ' +
     explref + ' CWPROOT=' + CWPROOT + ' ' +
     '''
     bulkmod=${SOURCES[0]} buoyancy=${SOURCES[1]} 
     explref=${TARGETS[0]} data_p=${SOURCES[3]}
     deriv=0 order=2 cfl=0.5 cmin=0.5 cmax=2.5 
     dmin=0.8 dmax=3.0 nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0
     dump_lda=1 dump_ldc=1 dump_term=1 sampord=1 adjtest=1
     ''',stdin=0,stdout=-1,workdir='$TARGET.work')

# near offset data
Flow('paracdpnearoff.su', 'paracdp.su', suwind + ' key=offset min=-270 max=-260 tmax=3')
Flow('paracdpnearoffagc.su', 'paracdpnearoff.su', sugain + ' agc=1')

# background bulk mod
Result('paracsqer','put d1=10 label1="Depth" unit1=m d2=12.5 label2="Midpoint" unit2=m unit=GPa | grey xinch=10 yinch=5 color=j scalebar=y barreverse=y')

# pspi image
Result('parapspifixagcfilt','put d1=10 label1="Depth" unit1=m d2=12.5 label2="Midpoint" unit2=m unit=GPa | grey xinch=10 yinch=5')

# stack, agc, filter
Result('parastackfix','parastackfix.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5')
Result('parastackfixagc','parastackfixagc.su', 'suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5')
Result('parastackfixagcfilt','parastackfixagcfilt.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5 clip=3')
Result('parastackfixagcfilt2','parastackfixagcfilt.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5 clip=3')

# agc'd near offset
Result('paracdpnearoffagc','paracdpnearoffagc.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5')
Result('paracdpnearoffagc2','paracdpnearoffagc.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5')

# exploding reflector data
Result('expldata','expldata.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5')

# cg 1 it image
Result('explnmo1it','put d1=10 label1="Depth" unit1=m d2=12.5 label2="Midpoint" unit2=m unit=GPa | grey xinch=10 yinch=5')

# cg 6 it image
Result('explnmo6it','put d1=10 label1="Depth" unit1=m d2=12.5 label2="Midpoint" unit2=m unit=GPa | grey xinch=10 yinch=5')

# 6 iteration sim data
Result('expldatanmo6it','expldatanmo6it.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5 clip=3')

# 6 iteration residual
Result('resdatanmo6it','resdatanmo6it.su','suread endian=0  read=data | put label1=Time label2=midpoint o2=1617.5 d2=25 unit1=s unit2=m | grey xinch=10 yinch=5 clip=3')

# rtm image
Result('reflnmo','put d1=10 label1="Depth" unit1=m d2=12.5 label2="Midpoint" unit2=m unit=GPa | grey xinch=10 yinch=5')

End()
