from rsf.proj import *

import os
import scenv

RSFROOT         = os.getenv('RSFROOT')
sfcp            = os.path.join(RSFROOT,'bin/sfcp')

print(sfcp)
MYAPPS          = os.getenv("MYAPPS")
python          = os.path.join(MYAPPS,'conda/miniconda/bin/python')

BASIC='../data'

# build list of data to import
srclist=[]
srclist.append('d1.su')
srclist.append('d11.su')
srclist.append('u1.su')
srclist.append('u11.su')
srclist.append('w1.su')
srclist.append('w11.su')
srclist.append('m.rsf')
srclist.append('m0.rsf')
srclist.append('bym.rsf')

# retrieve data
if not os.path.exists(BASIC):
    print('cannot find data source directory ' + BASIC)
    Exit(1)
else:
    for i in srclist:
        SRC = os.path.join(BASIC,i)
        if not os.path.exists(SRC):
            print('you must build the target ' + SRC)
            print('before building this project') 
            Exit(1)
        Flow(i,SRC,'/bin/cp ' + SRC + ' ' + i, stdin=0, stdout=-1)

# set up MSWI parameters
fdpars = 'order=2 sampord=1 nsnaps=20 cfl=0.5 cmin=1.0 cmax=3.0 dmin=0.8 dmax=3.0' + \
        ' ' + 'nl1=250 nr1=250 nl2=250 nr2=250 pmlampl=1.0 boundstest=True noisy=True'

smpars = 'rect1=10 rect2=10 repeat=2'

mswipars = 'alpha=0.0001 sigma=0.00001 rho=0.0025 kmax=1000 verbose=2'

lspars = 'lsmax=10 mured=0.5 muinc=1.8 gammared=0.1 gammainc=0.9'

# 11 shot at m0
descpars0 = r'descmax=0 desceps=0.01 descverbose=1 descout=\'outfile0.txt\' lsverbose=1'
pars = ' ' + fdpars + ' ' + smpars + ' ' + mswipars + ' ' + descpars0 + ' ' + lspars

Flow(['mest0.rsf', 'uest0.su'],
     ['m0.rsf', 'd11.su', 'u11.su', 'w11.su', 'bym.rsf'],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u msmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars, stdin=0, stdout=-1)

# 11 shot MSWI
descpars = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfile11.txt\' lsverbose=1'
pars = ' ' + fdpars + ' ' + smpars + ' ' + mswipars + ' ' + descpars + ' ' + lspars

Flow(['mest11.rsf', 'uest11.su'],
     ['m0.rsf', 'd11.su', 'u11.su', 'w11.su', 'bym.rsf'],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     ' /bin/cp ${SOURCES[2]} ${TARGETS[1]} && ' + \
     python + r' -u msmswi.py bulkmodout=\'${TARGETS[0]}\' filterout=\'${TARGETS[1]}\'' + \
     r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\' filterin=\'${SOURCES[2]}\'' + \
     r' buoyancy=\'${SOURCES[4]}\' source=\'${SOURCES[3]}\'' + pars, stdin=0, stdout=-1)

# FWI from final 11shot MSWI estimate
descparsfwi = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfilefwi.txt\' lsverbose=1'
fwipars = ' ' + fdpars + ' ' + smpars + ' ' + descparsfwi + ' ' + lspars
Flow('mestfwi.rsf',
    ['mest11.rsf', 'd11.su', 'w11.su', 'bym.rsf'],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' -u fwi.py bulkmodout=\'${TARGETS[0]}\'' + \
     	      r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\'' + \
              r' buoyancy=\'${SOURCES[3]}\' source=\'${SOURCES[2]}\'' + \
	      fwipars, stdin=0, stdout=-1)

Flow('resimfwi.su',['d11.su', 'w11.su', 'mestfwi.rsf', 'bym.rsf'],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)

# FWI from homogeneous bulk mod
descparsfwi0 = r'descmax=12 desceps=0.01 descverbose=1 descout=\'outfilefwi0.txt\' lsverbose=1'
fwi0pars = ' ' + fdpars + ' ' + smpars + ' ' + descparsfwi0 + ' ' + lspars
Flow('mestfwi0.rsf',
    ['m0.rsf', 'd11.su', 'w11.su', 'bym.rsf'],
     sfcp + ' ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' -u fwi.py bulkmodout=\'${TARGETS[0]}\'' + \
     	      r' bulkmodin=\'${SOURCES[0]}\' datain=\'${SOURCES[1]}\'' + \
              r' buoyancy=\'${SOURCES[3]}\' source=\'${SOURCES[2]}\'' + \
	      fwipars, stdin=0, stdout=-1)

Flow('resimfwi0.su',['d11.su', 'w11.su', 'mestfwi0.rsf', 'bym.rsf'],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)

Flow('sim0.su',['d11.su', 'w11.su', 'm0.rsf', 'bym.rsf'],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)

Flow('sim11.su',['d11.su', 'w11.su', 'mest11.rsf', 'bym.rsf'],
     ' /bin/cp ${SOURCES[0]} ${TARGETS[0]} && ' + \
     python + r' datasim.py bulkmod=\'${SOURCES[2]}\' data_p=\'${TARGETS[0]}\'' + \
     r' buoyancy=\'${SOURCES[3]}\' source_p=\'${SOURCES[1]}\'' + \
     ' ' + fdpars + ' partask=2', stdin=0, stdout=-1)