" ------------------------------- pcg params-------------------------------------",
  " For information on IWAVE FD and MPI parameters not described below, and",
  " general usage information for IWAVE applications, see self-doc for asg.x. ",
  " ",
  " Background parameters for this application are physical (no extension), only",
  " bulk modulus perturbation is extended - acts as subsurface offset dependent  ",
  " reflectivity. Extension may be trivial, that is, only one sample in the offset",
  " axis at offset zero, but the offset axis must be present."
  " ",
  " Model Parameters (prefixed with \"free\" and \"absb\"):",
  " ",
  "        bulkmod = <path>      input bulk modulus reference file, ",
  "                              determines simulation spatial grid,",
  "       buoyancy = <path>      input buoyancy (1/density) reference file, ",
  "                              must us same spatial grid as bulkmod",
  "    bulkmodpert = <path>      extended bulk modulus perturbation, input for",
  "                              modeling, output for migration/approximate inversion",
  " ",
  " Source Parameters (prefixed with \"free\" and \"absb\"):",
  "       source_p = <path>      RHS data for p update",
  "      source_v0 = <path>      RHS data for v0 update",
  "      source_v1 = <path>      RHS data for v1 update",
  "      source_v2 = <path>      RHS data for v2 update",
  " Note: at least one source file must be specified",
  " ",
  " Output Parameters (prefixed with \"free\" and \"absb\"):",
  "        data_p  = <path>      pressure",
  "        data_v0 = <path>      z component of velocity",
  "        data_v1 = <path>      x component of velocity",
  "        data_v2 = <path>      y component of velocity",
  " Note: at least one output file must be specified",
  " ",
  " REQUIRED FOR CURRENT IMPLEMENTATION:",
  " Make choices for both free and absorbing surface parameters, as both are ",
  " needed in approximate inversion. Prefix: \"free\" for free surface, \"absb\" for",
  " absorbing surface. Example: freebulkmod = <path>. Spatial fields (bulkmod, ",
  " buoyancy) for absorbing surface should differ from free surface by having ",
  " one or more rows of grid cells added on top of the model, extending the values",
  " on the top row of grid cells for the corresponding free surface parameter. Grid",
  " geometry for the two cases should otherwise be exactly the same. The free ",
  " surface grid should specify o1=0, that is, the top of the free surface model",
  " is at zero depth.",
  " ",
  " For example, if x[i1][i0] is one of the free surface arrays, sx0<=i0<=ex0,",
  " sx1<=i1<=ex1, then the corrsponding absorbing surface array y[i1][i0] should",
  " have index ranges sy0<=i0<=ex0, sy1<=i1<=ex1, sy0 < sx0, sy1<sx1, and ",
  " y[i1][i0] = x[i1][sx0] for sy0<=i0<sx0. It is easy to create either of these",
  " cases from the other in M8R using sfwindow and sfspray.",
  " ",
  " You must also specify a perturbational bulk modulus file (no buoyancy perturbation ",
  " in this app). Syntax is (prefix)bulkmodpert. The perturbation must be extended in",
  " subsurface offset (3rd index), like so: p[i2][i1][i0]. If the extension is trivial,",
  " that is, only offset zero is present, then it is only required to modify the RSF ",
  " header file to include gdim=3, dim=2, id3=101 (codes for internal extended axis),",
  " n3=1, o3=0, d3=[value of d2]. If extension is non-trivial (n3>1), build from non-",
  " extended fields using sfpad. ",
  " ",
  " The data and source arrays should also have free and absorbing surface instances",
  " specified, using the same prefixes, for instance freedata_p, absbsource_v1, and so",
  " on. These are su (segy) traces with selev, gelev < 0 in the free surface case, ",
  " selev, gelev = 0 in the absorbing surface case (and these properties are checked ",
  " in the code). Approximate inversion uses the shallow tow depth assumption, that is,",
  " source and receiver ghosts are presumed to accurately approximate source and receiver ",
  " z-derivatives of the data. Prototype data files on either type can be derived from the ",
  " other using sushw, and suitable source files using the iwave towed_array command.",
  " ",
  " On To-Do list: internalize the extension of the physical grid above the surface datum,",
  " eliminate requirement for two parallel sets of input files. (early spring 2018)"
  " ",
  " Appinv action choices:",
  " ",
  " deriv:   0 for forward and adjoint linearized maps, 1 for derivative of either",
  "          wrt background bulkmod",
  " adjoint: 0 for forward map, 1 for adjoint map (MaxIter=0)",
  " MaxIter: if > 0, number of (P)CG steps",
  " precond: 0 for ordinary migration or inversion, 1 for preconditioning by approximate",
  "          inverse (adjoint wrt weighted inner products in model and data spaces). In",
  "          particular, MaxIter=0 and precond=1 computes approximate inverse.",          
  " maxfreq: max temporal frequency in KHz. Required for filtering of FT driven computations.",
  " locut, lopas, hipas, hicut: optional corner frequencies for trapezoidal zero-phase bandpass",
  "          filter regularizing FT computation of derivatives and integrals. Default to 1/16,",
  "          1/8, 7/8, 15/16 * maxfreq.",
  " order:   spatial half-order - integer > 0 (typical choice is 4, for 8th spatial order FD)",
  " cfl:     proportion of max dt/dx - typical is 0.75",
  " cmin:    min permitted velocity (m/ms) - sanity check and spatial frequency scaling",
  " cmax:    max permitted velocity (m/ms) - used in dt comp, also spatial frequency scaling",
  " dmin:    min permitted density (g/cm^3) - sanity check",
  " dmax:    max permitted density (g/cm^3) - sanity check",
  " nsnaps:  number of checkpoints to use in optimal checkpointing algorithm to time-",
  "          reverse the source wavefield. Typical numbers are 10 or 20, yielding ",
  "          recomputation overhead of 3-5 for O(10^4) time steps. Checkpoints are",
  "          stored in-core in the current implementation. Meaningful only for adjoint=1,",
  "          but required in that case.",
  " ",
  " Boundary Parameters: (replace pml parameters in other ASG applications):",
  " ",
  " freesurface: 1 for pressure-free surface (z=0), 0 for absorbing surface.",
  " pmlwidth:    width of pml zone on all absorbing boundaries (in m) - typical choice is 0.5 * ",
  "              dominant wavelength.",
  " pmlampl:     scale of pml coefficients - typical choice is 1.0.",
  " ",
  " Mute, Taper Parameters:",
  " ",
  " mute_slope=0.0: t/x slope of linear top mute",
  " mute_width=0.0: width of mute linear taper zone (ms)",
  " mute_zotime=0.0: time at zero offet (ms)",
  " top=0.0: top of taper for pertbulkmod (m) - depth below z=0",
  " bot=0.0: bottom of taper for perbulkmod (m) - depth below z=0",
  " ",
  " NOTE: for both preconditioned and unpreconditioned adjoint, better results are obtained",
  " if direct wave and (to extend possible) diving wave energy are muted out of data, and a",
  " taper width of at least a wavelength is used. For iterative preconditioned inversion, ",
  " convergence requires that all iterates avoid introducing horizontally or downward",
  " propagating reflective energy, that is, pertbulkmod should vanish near and above source",
  " and receiver depths. Achieve this by setting the top taper at a depth > -z_s, -z_r ",
  " (elevations!), and the bottom taper about a wavelength or so below. This choice confines",
  " reflectors to a zone well below the sources and receivers. Assuming that these are located",
  " in a homogeneous (water) layer, no reflectors can develop above the top taper during ",
  " iterative inversion, so no horizontally propagating energy can be generative and the",
  " data-side preconditioning operator remains positive definite.",
  " ",
  " Conjugate Gradient Parameters: (MaxIter>0 for iterative inversion)",
  " ",
  " MaxIter = 0",
  "   = maximum permitted iterations; = 0 for adjoint application",
  " ResidualTol = 100.0*numeric_limits<atype>::epsilon()",
  "   = relative stopping tolerance for residual norm decrease",
  " GradientTol = 100.0*numeric_limits<atype>::epsilon()",
  "   = relative stopping tolerance for normal residual decrease",
  " MaxStep = numeric_limits<atype>::max()",
  "   = max step length (trust radius)",
  " ",
  " Example parameter list for free surface Born modeling witn 64 parallel shot ",
  " computations (same parameter list works for migration - in the former case, ",
  " freedata_p is output, freebulkmodpert is input, in the latter case the roles",
  " are switched and adjoint=1):",
  " ",
  " order=4 adjoint=0 cfl=0.5 cmin=1.0 cmax=3.0 dmin=0.8 dmax=3.0 ",
  " sampord=1 pmlwidth=250 pmlampl=1.0 dump_term=0 ",
  " dump_lda=0 dump_ldc=0 printact=0 partask=64 freesurface=1",
  " freebulkmod=<path> freebuoyancy=<path> freebulkmodpert=<path> ",
  " absbbulkmod=<path> absbbuoyancy=<path> absbbulkmodpert=<path>",
  " freesource_p=<path> absbsource_p=<path> freedata_p=<path> absbdata_p=<path>",
  " ",
  " Example parameter list for approximate inversion of free surface data:",
  " ",
  " order=4 adjoint=1 cfl=0.5 cmin=1.0 cmax=3.0 dmin=0.8 dmax=3.0 ",
  " sampord=1 pmlwidth=250 pmlampl=1.0 dump_term=0 ",
  " dump_lda=0 dump_ldc=0 printact=0 partask=64 freesurface=1",
  " precond=1 ft=1 ab=1 maxfreq=0.04 nsnaps=20 ",
  " freebulkmod=<path> freebuoyancy=<path> freebulkmodpert=<path> ",
  " absbbulkmod=<path> absbbuoyancy=<path> absbbulkmodpert=<path>",
  " freesource_p=<path> absbsource_p=<path> freedata_p=<path> absbdata_p=<path>",
  " ",
  " Example parameter list for preconditioned iterative inversion of free",
  " surface data,using 10 PCG iterations:",
  " ",
  " order=4 adjoint=1 cfl=0.5 cmin=1.0 cmax=3.0 dmin=0.8 dmax=3.0 ",
  " sampord=1 pmlwidth=250 pmlampl=1.0 dump_term=0 ",
  " dump_lda=0 dump_ldc=0 printact=0 partask=64 freesurface=1",
  " precond=1 ft=1 ab=1 maxfreq=0.04 nsnaps=20 ",
  " freebulkmod=<path> freebuoyancy=<path> freebulkmodpert=<path> ",
  " absbbulkmod=<path> absbbuoyancy=<path> absbbulkmodpert=<path>",
  " freesource_p=<path> absbsource_p=<path> ",
  " freedata_p=<path> absbdata_p=<path>",
  " ResidualTol=0.01 GradientTol=0.01 MaxIter=10 ",
  " outfile=cgne.rpt ",
  " mute_slope=0.75 mute_width=200 mute_zotime=0.25 ",
  " top=200.0 bot=350.0 ",
  " ",
  " In all of these examples, partask=64 signifies that 64 shots will be ",
  " modeled or migrated simultaneously. See other self-docs and the report",
  " \"Parallel IWAVE\" for more on various levels of parallelism in IWAVE.",
  " ",
" ------------------------------ pcg params-------------------------------------",
