"/******************************************************************************",
  " * Acoustic variable density staggered grid extended linearized forward and   * ",
  " * adjoint modeling and approximate inversion in 2D subsurface offset domain  * ",
  " * (3D coming soon!)                                                          * ",
  " *                                                                            * ",
  " * Based on extended linearized map                                           * ",
  " *   extended bulkmod perturbation ---> data perturbation                     * ",
  " *   (buoyancy/density perturbation = 0)                                      * ",
  " *                                                                            * ",
  " * Algorithm: by Raanan Dafni and Willaim W. Symes, based on papers by        * ",
  " * Jie Hou and William W. Symes, Geophysics 2015-2017,                        * ",  
  " * Code: Raanan Dafni, Igor Terentyev, Tanya Vdovina, Xin Wang, Rami Nammour, *",
  " *   Dong Sun, Mario J. Bencomo, Muhong Zhou, Yin Huang, and William W. Symes *",
  " ******************************************************************************/",
  " ",
