" ------------------------------ asg base params--------------------------------",
  " ",
  "  ====== BASE PARAMETERS FOR ACOUSTIC STAGGERERD GRID SIMULATION ======= ",
  " ",
  " Model Parameters, RSF format files:",
  "        bulkmod = <string>*   bulk modulus, determines simulation ",
  "                              spatial grid,",
  "       buoyancy = <string>*   buoyancy (1/density) must define,",
  "                              same spatial grid as bulkmod",
  " ",
  " Source Parameters, SU format files:",
  "       source_p = <string>    RHS data for p update",
  "      source_v0 = <string>    RHS data for v0 update",
  "      source_v1 = <string>    RHS data for v1 update",
  "      source_v2 = <string>    RHS data for v2 update",
  " Note: at least one source file must be specified",
  " ",
  " Data Parameters, SU format:",
  "        data_p  = <string>    pressure",
  "        data_v0 = <string>    z component of velocity",
  "        data_v1 = <string>    x component of velocity",
  "        data_v2 = <string>    y component of velocity",
    " Note: at least one data file must be specified",
  " ",
" ------------------------------ asg base params--------------------------------",
