#############################################################################
###################### COMMON DEFINITIONS - DO NOT ALTER ####################
#############################################################################
from rsf.proj import *

import os

#############################################################################
###################### END COMMON DEFINITIONS ###############################
#############################################################################

######## you use abbreviations
# example:
#          CWPROOT         = os.getenv('CWPROOT')
#          ...
#          sunull          = os.path.join(CWPROOT,'bin/sunull')
CWPROOT         = os.getenv('CWPROOT')
a2b             = os.path.join(CWPROOT,'bin/a2b')
b2a             = os.path.join(CWPROOT,'bin/b2a')
farith          = os.path.join(CWPROOT,'bin/farith')
suwind          = os.path.join(CWPROOT,'bin/suwind')
susort          = os.path.join(CWPROOT,'bin/susort')
sumute          = os.path.join(CWPROOT,'bin/sumute')
sufilter        = os.path.join(CWPROOT,'bin/sufilter')
sustack         = os.path.join(CWPROOT,'bin/sustack')
sugain          = os.path.join(CWPROOT,'bin/sugain')
transp          = os.path.join(CWPROOT,'bin/transp')
sufilter        = os.path.join(CWPROOT,'bin/sufilter')
sufft           = os.path.join(CWPROOT,'bin/sufft')
suamp           = os.path.join(CWPROOT,'bin/suamp')
suspike         = os.path.join(CWPROOT,'bin/suspike')
sushw           = os.path.join(CWPROOT,'bin/sushw')
suchw           = os.path.join(CWPROOT,'bin/suchw')
sufrac          = os.path.join(CWPROOT,'bin/sufrac')
suop2           = os.path.join(CWPROOT,'bin/suop2')
suop            = os.path.join(CWPROOT,'bin/suop')
sunull          = os.path.join(CWPROOT,'bin/sunull')
suwaveform      = os.path.join(CWPROOT,'bin/suwaveform')
sumean          = os.path.join(CWPROOT,'bin/sumean')
RSFROOT         = os.getenv('RSFROOT')
sfsuread        = os.path.join(RSFROOT,'bin/sfsuread')
sfmatmult       = os.path.join(RSFROOT,'bin/sfmatmult')
sfwindow        = os.path.join(RSFROOT,'bin/sfwindow')
sfadd           = os.path.join(RSFROOT,'bin/sfadd')
sfget           = os.path.join(RSFROOT,'bin/sfget')
sfspray         = os.path.join(RSFROOT,'bin/sfspray')
sfcp            = os.path.join(RSFROOT,'bin/sfcp')

HERE            = os.getcwd()
PROJ            = os.path.dirname(HERE)

########### archive - unarchive ##############

# generic result directory
#res = {'mestfwi0': ['.rsf','m'], 'resimmestfwi0': ['.su','d'], 'uest0': ['.su', 'u'], 'uest1': ['.su', 'u'], 'mestmswi': ['.rsf', 'm'], 'uestmswi': ['.su', 'u'], 'mestmswifwi': ['.rsf', 'm'], 'resimmestmswi': ['.su', 'd'], 'resimmestmswifwi': ['.su', 'd'], 'residmestfwi0': ['.su','d'], 'residmestmswi': ['.su', 'd'], 'residmestmswifwi': ['.su', 'd']}
res = {'uest0': ['.su', 'u'], 'uest1': ['.su', 'u'], 'mestmswi': ['.rsf', 'm'], 'uestmswi': ['.su', 'u'], 'mestmswifwi': ['.rsf', 'm'], 'resimmestmswi': ['.su', 'd'], 'resimmestmswifwi': ['.su', 'd'], 'residmestmswi': ['.su', 'd'], 'residmestmswifwi': ['.su', 'd']}

# data dictionaries
#dat = {'cwd20': '.su', 'chwd20': '.su', 'cowd20': '.su', 'fcwd20': '.su', 'm': '.rsf', 'dcwm': '.rsf'}
dat = {'cwd20': '.su', 'chwd20': '.su', 'dcowd20': '.su', 'dcwd20': '.su', 'm': '.rsf', 'dcwm': '.rsf', 'camcwd20': '.su', 'cambulk': '.rsf'}

# result list
# reslist = ['cwlens20', 'mnqcaustic20',  'mcaustic20', 'cam20']
reslist = ['cam20']

# retrieve and plot data

DATADIR = os.path.join(PROJ,'data')
if not os.path.exists(DATADIR):
    print('cannot find data source directory ' + DATADIR)
    Exit(1)
else:
    for d in dat.keys():
        SRC = os.path.join(DATADIR, d + dat[d])
        print('SRC = ' + SRC)
        if not os.path.exists(SRC):        
            print('source data: you must build the target ' + SRC)
            print('before building this project') 
            Exit(1)
        if dat[d] == '.su':
#             if d == 'fcwd20':
             if d == 'dcwd20' or d == 'camcwd20':   
                 Result(d, SRC, 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')
             else:
                 Result(d, SRC, 'suread endian=0 read=data | window min1=1.8 max1=3.2 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')
        else:
            Result(d, SRC, 'grey minval=2.0 maxval=5.0 scalebar=y color=j xinch=10 yinch=4 wanttitle=n')

for d in reslist:
    RESDIR = os.path.join(PROJ,d)
    if not os.path.exists(RESDIR):
        print('cannot find result directory ' + RESDIR)
        Exit(1)
    else:
        for k in res.keys():
            SRC = os.path.join(RESDIR,k + res[k][0])
            if not os.path.exists(SRC):        
                print('source data: you must build the target ' + SRC)
                print('before building this project') 
                Exit(1)
            if res[k][0] == '.su':
                if res[k][1] == 'd':
#                    if d == 'caustic20':
                    if d == 'mcaustic20' or d == 'cam20':
                        Result(d + k, SRC, 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')
                    else: 
                        Result(d + k, SRC, 'suread endian=0 read=data | window min1=1.8 max1=3.2 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')
                else:
                    Result(d + k, SRC, 'suread endian=0 read=data | window min1=-0.4 max1=0.4 | grey clip=0.02 d2num=0.1 color=j xinch=10 yinch=6 wanttitle=n')
            else:
                Result(d + k, SRC, 'grey minval=2.0 maxval=5.0 scalebar=y color=j xinch=10 yinch=4 wanttitle=n')


######################### extra plots for cam20 ###########################

Result('cam20mestmswifwifine','../cam20/mestmswifwifine.rsf', 'grey minval=2.0 maxval=5.0 scalebar=y color=j xinch=10 yinch=4 wanttitle=n')

Result('cam20resimmestmswifwifine', '../cam20/resimmestmswifwifine.su', 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('cam20residmestmswifwifine', '../cam20/residmestmswifwifine.su', 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('cam20uest2', '../cam20/uest2.su','suread endian=0 read=data | window min1=-0.4 max1=0.4 | grey clip=0.02 color=j xinch=10 yinch=6 wanttitle=n')

Result('cam20uest2', '../cam20/uest2.su','suread endian=0 read=data | window min1=-0.4 max1=0.4 | grey clip=0.02 color=j xinch=10 yinch=6 wanttitle=n')


######################## extra plots for mcaustic20 #######################

Result('mcaustic20mestmswicont','../mcaustic20/mestmswicont.rsf', 'grey minval=2.0 maxval=5.0 scalebar=y color=j xinch=10 yinch=4 wanttitle=n')

Result('mcaustic20resimmestmswicont', '../mcaustic20/resimmestmswicont.su', 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('mcaustic20residmestmswicont', '../mcaustic20/residmestmswicont.su', 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('mcaustic20uestmswicont', '../mcaustic20/uestmswicont.su','suread endian=0 read=data | window min1=-0.4 max1=0.4 | grey clip=0.02 color=j xinch=10 yinch=6 wanttitle=n')

Result('mcaustic20mestmswifwicont','../mcaustic20/mestmswifwicont.rsf', 'grey minval=2.0 maxval=5.0 scalebar=y color=j xinch=10 yinch=4 wanttitle=n')

Result('mcaustic20resimmestmswifwicont', '../mcaustic20/resimmestmswifwicont.su', 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('mcaustic20residmestmswifwicont', '../mcaustic20/residmestmswifwicont.su', 'suread endian=0 read=data | window min1=2.5 max1=4.0 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('mcaustic20uest2', '../mcaustic20/uest2.su','suread endian=0 read=data | window min1=-0.4 max1=0.4 | grey clip=0.02 color=j xinch=10 yinch=6 wanttitle=n')

######################### extra plots for cwlens20 ######################

Result('cwlens20mestfwi0', '../cwlens20/mestfwi0.rsf', 'grey minval=2.0 maxval=5.0 scalebar=y color=j xinch=10 yinch=4 wanttitle=n')

Result('cwlens20resimmestfwi0', '../cwlens20/resimmestfwi0.su', 'suread endian=0 read=data | window min1=1.8 max1=3.2 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

Result('cwlens20residmestfwi0', '../cwlens20/residmestfwi0.su', 'suread endian=0 read=data | window min1=1.8 max1=3.2 | grey clip=0.005 color=j xinch=10 yinch=4 wanttitle=n')

End()