

extern "C" void asg_pstep2d(float ** restrict bulk,
                            float ** restrict p0, float ** restrict p1,
                            float ** restrict v0, float ** restrict v1,
                            float ** restrict ep, float ** restrict epp,
                            float * restrict sdiv,
                            const int * gsc, const int * gec,
                            const int * lbc, const int * rbc,
                            int maxoff, float ** restrict c);
extern "C" void asg_pstep2d_d(float ** restrict bulk, float ** restrict dbulk,
                              float ** restrict p0, float ** restrict dp0,
                              float ** restrict p1, float ** restrict dp1,
                              float ** restrict v0, float ** restrict dv0,
                              float ** restrict v1, float ** restrict dv1,
                              float ** restrict ep, float ** restrict epp,
                              float * restrict sdiv,
                              float * restrict dsdiv,
                              int * gsc, int * gec,
                              int * lbc, int * rbc,
                              int maxoff, float ** restrict c);
extern "C" void asg_pstep2d_b(float ** restrict bulk, float ** restrict dbulk,
                              float ** restrict p0, float ** restrict dp0,
                              float ** restrict p1, float ** restrict dp1,
                              float ** restrict v0, float ** restrict dv0,
                              float ** restrict v1, float ** restrict dv1,
                              float ** restrict ep, float ** restrict epp,
                              float * restrict sdiv,
                              float * restrict dsdiv,
                              int * gsc, int * gec,
                              int * lbc, int * rbc,
                              int maxoff, float ** restrict c);

extern "C" void asg_pstep3d(float *** restrict bulk,
                            float *** restrict p0, float *** restrict p1, float *** restrict p2,
                            float *** restrict v0, float *** restrict v1, float *** restrict v2,
                            float ** restrict ep, float ** restrict epp,
                            float * restrict sdiv,
                            const int * gsc, const int * gec,
                            const int * lbc, const int * rbc,
                            int maxoff, float ** restrict c);

extern "C" void asg_vstep2d(float ** restrict buoy,
                            float ** restrict p0,float ** restrict p1,
                            float ** restrict v0,float ** restrict v1,
                            float ** restrict ev, float ** restrict evp,
                            float ** restrict gradp,
                            const int * gsc_v0, const int * gec_v0,
                            const int * gsc_v1, const int * gec_v1,
                            const int * lbc, const int * rbc,
                            int maxoff,float ** restrict c);

extern "C" void asg_vstep2d_d(float ** restrict buoy, float ** restrict dbuoy,
                              float ** restrict p0, float ** restrict dp0,
                              float ** restrict p1, float ** restrict dp1,
                              float ** restrict v0, float ** restrict dv0,
                              float ** restrict v1, float ** restrict dv1,
                              float ** restrict ev, float ** restrict evp,
                              float ** restrict gradp,
                              float ** restrict dgradp,
                              int * gsc_v0, int * gec_v0,
                              int * gsc_v1, int * gec_v1,
                              int * lbc, int * rbc,
                              int maxoff, float ** restrict c);
extern "C" void asg_vstep2d_b(float ** restrict buoy, float ** restrict dbuoy,
                              float ** restrict p0, float ** restrict dp0,
                              float ** restrict p1, float ** restrict dp1,
                              float ** restrict v0, float ** restrict dv0,
                              float ** restrict v1, float ** restrict dv1,
                              float ** restrict ep, float ** restrict epp,
                              float ** restrict gradp,
                              float ** restrict dgradp,
                              int * gsc_v0, int * gec_v0,
                              int * gsc_v1, int * gec_v1,
                              int * lbc, int * rbc,
                              int maxoff, float ** restrict c);

extern "C" void asg_vstep3d(float *** restrict buoy,
                            float *** restrict p0,float *** restrict p1, float *** restrict p2,
                            float *** restrict v0,float *** restrict v1, float *** restrict v2,
                            float ** restrict ev, float ** restrict evp,
                            float ** restrict gradp,
                            int * gsc_v0, int * gec_v0,
                            int * gsc_v1, int * gec_v1,
                            int * gsc_v2, int * gec_v2,
                            int * lbc, int * rbc,
                            int maxoff,float ** restrict c);
