#!/bin/python
from rsf.proj import *

#   GENERATE 2D TWO LAYER MODEL WITH HORIZONTAL INTERFACE,
#   GRID INTERFACE IS AWAY FROM THE MATERIAL INTERFACE
Flow('top',None,
    '''spike d1=0.5 n1=321 d2=0.5 n2=321 d3=0.5 n3=145 mag=1 |
        put label1="x" unit1="m" |
        put label2="y" unit2="m" |
        put label3="z" unit3="m" ''',stdin=0)
Flow('bottom',None,
    '''spike d1=0.5 n1=321 d2=0.5 n2=321 d3=0.5 n3=176 mag=2 |
        put label1="x" unit1="m" |
        put label2="y" unit2="m" |
        put label3="z" unit3="m" ''',stdin=0)
Flow('layer_model',['top', 'bottom'],'''cat ${SOURCES[1:-1]} axis=3''')
Flow('top_mask','layer_model','''mask max=1.5 | scale dscale=1.0 ''')
Flow('bottom_mask','layer_model','''mask min=1.5 | scale dscale=1.0 ''')


# rho(2.5~2.65)
Flow('rho',['top_mask','bottom_mask'],
    '''add ${SOURCES[0]} ${SOURCES[1]} scale=2.5,2.65''',stdin=0)
# vs(1~2)
Flow('vs',['top_mask','bottom_mask'],
    '''add ${SOURCES[0]} ${SOURCES[1]} scale=1,2''',stdin=0)
# vp(2~4)
Flow('vp',['top_mask','bottom_mask'],
    '''add ${SOURCES[0]} ${SOURCES[1]} scale=2,4''',stdin=0)

for file in ['rho','vp','vs']:
    Plot(file,file,'''window f2=125 n2=1 |
        sfgrey color=e scalebar=y title=\"%s\" '''%(file))

