/*        Generated by TAPENADE     (INRIA, Ecuador team)
	  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/

#include "cstd.h"

/*
  Differentiation of asg2dtap in reverse (adjoint) mode:
  gradient     of useful results: **v0 **v1 **p0 **p1
  with respect to varying inputs: **v0 **v1 ***bulk **buoy **p0
  **p1
  RW status of diff variables: **v0:in-out **v1:in-out ***bulk:out
  **buoy:out **p0:in-out **p1:in-out
  Plus diff mem management of: v0:in *v0:in v1:in *v1:in bulk:in
  *bulk:in **bulk:in buoy:in *buoy:in p0:in *p0:in
  p1:in *p1:in sdiv:in *sdiv:in sdivb:in *sdivb:in
  gradp0:in gradp1:in
*/
void basg2d_b(float ** restrict bulk, float *** restrict bulkb, float ** 
	      restrict buoy, float ** restrict buoyb, float ** restrict p0, float **
	      restrict p0b, float ** restrict p1, float ** restrict p1b, float ** 
	      restrict v0, float ** restrict v0b, float ** restrict v1, float ** 
	      restrict v1b, float ** restrict ep, float ** restrict epp, float ** 
	      restrict ev, float ** restrict evp, float ** restrict sdiv, float ** 
	      restrict sdivb0, float ** restrict sdivb, float ** restrict sdivbb, 
	      float * restrict gradp0, float * restrict gradp0b, 
	      float * restrict gradp1, float * restrict gradp1b, int *
	      gsc_p, int *gec_p, int *gsc_v0, int *gec_v0, int *gsc_v1, int *gec_v1,
	      int *lbc, int *rbc, int ihmax, int maxoff, float ** restrict c, FILE *
	      stream) {
  int i0, i1;
  int ioff;
  {
    int ih;
    int sh;
    int eh;
    float tempb;
    float tempb0;
    float tempb1;
    float tempb2;
    float tempb3;
    float tempb4;
    float tempb5;
    float tempb6;
    float tempb7;
    float tempb8;
    float tmp;
    float tmp1;
    float tmp2;
    
    float tmpb;
    float tmpb1;
    float tmpb2;
    float tmpb4;
    float tmpb5;
    float tmpb6;
    float tmp0;
    float tmpb0;
    float tmpb3;

    // fprintf(stderr,"1\n");
    for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
      //      // fprintf(stderr,"1a i1=%d gsc_p[1]=%d gec_p[1]=%d\n",i1,gsc_p[1],gec_p[1]);
      memset((char *)(sdiv[i1-gsc_p[1]]),  0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      memset((char *)(sdivb[i1-gsc_p[1]]), 0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      //      // fprintf(stderr,"1b\n");      
      for (ioff = 0; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0)
	  sdiv[i1 - gsc_p[1]][i0 - gsc_p[0]] +=
	    (c[0][ioff]*(v0[i1][i0+ioff]-v0[i1][i0-ioff-1]) +
	     c[1][ioff]*(v1[i1+ioff][i0]-v1[i1-ioff-1][i0]));
    }
    // fprintf(stderr,"2\n");    
    for (i1 = gsc_p[1]; i1 <= gec_p[1]; i1++) {
#pragma ivdep
      for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	sdivb[i1 - gsc_p[1]][i0 - gsc_p[0]] +=
	  bulk[i1][i0]*sdiv[i1-gsc_p[1]][i0-gsc_p[0]];
      }
    }
    
    // fprintf(stderr,"3\n");
    for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1)
#pragma ivdep
      for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	p0[i1][i0] = (ep[0][i0]*p0[i1][i0]-sdivb[i1-gsc_p[1]][i0-gsc_p[0]])*epp[0][i0];
	p1[i1][i0] = (ep[1][i1]*p1[i1][i0]-sdivb[i1-gsc_p[1]][i0-gsc_p[0]])*epp[1][i1];
      }
    // fprintf(stderr,"4\n");

    if (lbc[0]) {
      for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
	p0[i1][gsc_p[0] - 1] = 0.0f;
	for (ioff = 1; ioff < maxoff; ++ioff) {
	  tmp = -p0[i1][gsc_p[0]+ioff-1];
	  p0[i1][gsc_p[0] - ioff - 1] = tmp;
	}
      }
    }

    if (rbc[0]) {
      for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
	p0[i1][gec_p[0] + 1] = 0.0f;
	for (ioff = 1; ioff < maxoff; ++ioff) {
	  tmp0 = -p0[i1][gec_p[0]-ioff+1];
	  p0[i1][gec_p[0] + ioff + 1] = tmp0;
	}
      }
    }
    
    if (lbc[1]) {
      for (ioff = 0; ioff < maxoff; ++ioff) {
#pragma ivdep
	for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	  tmp1 = -p1[gsc_p[1]+ioff-1][i0];
	  p1[gsc_p[1] - ioff - 1][i0] = (ioff < 1 ? 0.0f : tmp1);
	}
      }
    }
    
    if (rbc[1]) {
      for (ioff = 1; ioff < maxoff; ++ioff) {
#pragma ivdep
	for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	  tmp2 = -p1[gec_p[1]-ioff+1][i0];
	  p1[gec_p[1] + ioff + 1][i0] = (ioff < 1 ? 0.0f : tmp2);
	}
      }
    }
    
    // fprintf(stderr,"6\n");
    
    if (rbc[1])
      for (ioff = maxoff-1; ioff > 0; --ioff)
#pragma ivdep
	for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
	  tmpb6 = v1b[gec_v1[1] + ioff][i0];
	  v1b[gec_v1[1] + ioff][i0] = 0.0;
	  v1b[gec_v1[1] - ioff + 1][i0] = v1b[gec_v1[1] - ioff + 1][i0] + tmpb6;
	}

    if (lbc[1])
      for (ioff = maxoff-1; ioff > 0; --ioff)
#pragma ivdep
	for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
	  tmpb5 = v1b[gsc_v1[1] - ioff][i0];
	  v1b[gsc_v1[1] - ioff][i0] = 0.0;
	  v1b[gsc_v1[1] + ioff - 1][i0] = v1b[gsc_v1[1] + ioff - 1][i0] + tmpb5;
	}
    // fprintf(stderr,"8\n");

    if (rbc[0])
      for (ioff = maxoff-1; ioff > 0; --ioff)
	for (i1 = gec_v0[1]; i1 > gsc_v0[1]-1; --i1) {
	  tmpb4 = v0b[i1][gec_v0[0] + ioff];
	  v0b[i1][gec_v0[0] + ioff] = 0.0;
	  v0b[i1][gec_v0[0] - ioff + 1] = v0b[i1][gec_v0[0] - ioff + 1] + tmpb4;
	}
    // fprintf(stderr,"9\n");

    if (lbc[0])
      for (ioff = maxoff-1; ioff > 0; --ioff)
	for (i1 = gec_v0[1]; i1 > gsc_v0[1]-1; --i1) {
	  tmpb3 = v0b[i1][gsc_v0[0] - ioff];
	  v0b[i1][gsc_v0[0] - ioff] = 0.0;
	  v0b[i1][gsc_v0[0] + ioff - 1] = v0b[i1][gsc_v0[0] + ioff - 1] + tmpb3;
	}
    // fprintf(stderr,"10\n");

    for (i1 = gec_v1[1]; i1 > gsc_v1[1]-1; --i1) {
      memset((char *)gradp1, 0, (gec_v1[0]-gsc_v1[0]+1)*sizeof(float));
      memset((char *)gradp1b, 0, (gec_v1[0]-gsc_v1[0]+1)*sizeof(float));
      for (ioff = 0; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
	  gradp1[i0 - gsc_v1[0]] = gradp1[i0 - gsc_v1[0]] + c[1][ioff]
	    *(p1[i1+ioff+1][i0]-p1[i1-ioff][i0]);
	}
#pragma ivdep      
      for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
	tempb7 = evp[1][i1]*v1b[i1][i0];
	tempb8 = -(0.5f*gradp1[i0-gsc_v1[0]]*tempb7);
	buoyb[i1][i0] = buoyb[i1][i0] + tempb8;
	buoyb[i1 + 1][i0] = buoyb[i1 + 1][i0] + tempb8;
	gradp1b[i0 - gsc_v1[0]] = gradp1b[i0 - gsc_v1[0]]
	  - 0.5f*(buoy[i1][i0]+buoy[i1+1][i0])*tempb7;
	v1b[i1][i0] = ev[1][i1]*tempb7;
      }
      for (ioff = maxoff-1; ioff > -1; --ioff)
#pragma ivdep
	for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
	  tempb6 = c[1][ioff]*gradp1b[i0-gsc_v1[0]];
	  p1b[i1 + ioff + 1][i0] = p1b[i1 + ioff + 1][i0] + tempb6;
	  p1b[i1 - ioff][i0] = p1b[i1 - ioff][i0] - tempb6;
	}
    }
    // fprintf(stderr,"12\n");

    for (i1 = gec_v0[1]; i1 > gsc_v0[1]-1; --i1) {
      memset((char *)gradp0, 0, (gec_v0[0]-gsc_v0[0]+1)*sizeof(float));
      memset((char *)gradp0b, 0, (gec_v0[0]-gsc_v0[0]+1)*sizeof(float));
      for (ioff = 0; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
	  gradp0[i0 - gsc_v0[0]] = gradp0[i0 - gsc_v0[0]] + c[0][ioff]
	    *(p0[i1][i0+ioff+1]-p0[i1][i0-ioff]);
	}
#pragma ivdep
      for (i0 = gec_v0[0]; i0 > gsc_v0[0]-1; --i0) {
	tempb4 = evp[0][i0]*v0b[i1][i0];
	tempb5 = -(0.5f*gradp0[i0-gsc_v0[0]]*tempb4);
	buoyb[i1][i0] = buoyb[i1][i0] + tempb5;
	buoyb[i1][i0 + 1] = buoyb[i1][i0 + 1] + tempb5;
	gradp0b[i0 - gsc_v0[0]] +=  - 0.5f*(buoy[
						 i1][i0]+buoy[i1][i0+1])*tempb4;
	v0b[i1][i0] = ev[0][i0]*tempb4;
      }
      for (ioff = maxoff-1; ioff > -1; --ioff)
#pragma ivdep
	for (i0 = gec_v0[0]; i0 > gsc_v0[0]-1; --i0) {
	  tempb3 = c[0][ioff]*gradp0b[i0-gsc_v0[0]];
	  p0b[i1][i0 + ioff + 1] = p0b[i1][i0 + ioff + 1] + tempb3;
	  p0b[i1][i0 - ioff] = p0b[i1][i0 - ioff] - tempb3;
	}
    }

    // fprintf(stderr,"13\n");

    if (rbc[1])
      for (ioff = maxoff-1; ioff > 0; --ioff) {
#pragma ivdep
	for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	  tmpb2 = p1b[gec_p[1] + ioff + 1][i0];
	  p1b[gec_p[1] + ioff + 1][i0] = 0.0;
	  p1b[gec_p[1] - ioff + 1][i0] =
	    ((ioff < 1) ? 0.0f : p1b[gec_p[1] - ioff + 1][i0] - tmpb2);
	}
	//	p1b[gec_p[1] + 1][i0] = 0.0;
      }
    // fprintf(stderr,"14\n");
    
    if (lbc[1])
      for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	for (ioff = maxoff-1; ioff > 0; --ioff) {
	  tmpb1 = p1b[gsc_p[1] - ioff - 1][i0];
	  p1b[gsc_p[1] - ioff - 1][i0] = 0.0;
	  p1b[gsc_p[1] + ioff - 1][i0] = p1b[gsc_p[1] + ioff - 1][i0] 
	    - tmpb1;
	}
	p1b[gsc_p[1] - 1][i0] = 0.0;
      }
    // fprintf(stderr,"15\n");

    if (rbc[0])
      for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
	for (ioff = maxoff-1; ioff > 0; --ioff) {
	  tmpb0 = p0b[i1][gec_p[0] + ioff + 1];
	  p0b[i1][gec_p[0] + ioff + 1] = 0.0;
	  p0b[i1][gec_p[0] - ioff + 1] = p0b[i1][gec_p[0] - ioff + 1] 
	    - tmpb0;
	}
	p0b[i1][gec_p[0] + 1] = 0.0;
      }
    // fprintf(stderr,"16\n");

    if (lbc[0])
      for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
	for (ioff = maxoff-1; ioff > 0; --ioff) {
	  tmpb = p0b[i1][gsc_p[0] - ioff - 1];
	  p0b[i1][gsc_p[0] - ioff - 1] = 0.0;
	  p0b[i1][gsc_p[0] + ioff - 1] = p0b[i1][gsc_p[0] + ioff - 1] 
	    - tmpb;
	}
	p0b[i1][gsc_p[0] - 1] = 0.0;
      }

    // fprintf(stderr,"17\n");

    for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
      memset((char *)(sdivbb[i1-gsc_p[1]]), 0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      memset((char *)(sdivb0[i1-gsc_p[1]]), 0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
    
      // fprintf(stderr,"18\n");
#pragma ivdep
      
      for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	tempb1 = epp[1][i1]*p1b[i1][i0];
	sdivbb[i1 - gsc_p[1]][i0 - gsc_p[0]] -= tempb1;
	p1b[i1][i0] = ep[1][i1]*tempb1;
	tempb2 = epp[0][i0]*p0b[i1][i0];
	sdivbb[i1 - gsc_p[1]][i0 - gsc_p[0]] -= tempb2;
	p0b[i1][i0] = ep[0][i0]*tempb2;
      }
    }

    // fprintf(stderr,"19\n");
    float sd=0.0;
    float sb=0.0;
    for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
      for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	sb+=sdivbb[i1-gsc_p[1]][i0-gsc_p[0]]*sdivbb[i1-gsc_p[1]][i0-gsc_p[0]];
	sd+=sdiv[i1-gsc_p[1]][i0-gsc_p[0]]*sdiv[i1-gsc_p[1]][i0-gsc_p[0]];
      }
    }
    fprintf(stderr,"sd=%g sb=%g\n",sd,sb);
    
    for (ih = ihmax; ih > -1-ihmax; --ih) {
      if (ih <= 0) {
	sh = gsc_p[1] - ih;
	eh = gec_p[1];
      } else {
	sh = gsc_p[1];
	eh = gec_p[1] - ih;
      }
      for (i1 = eh; i1 > sh-1; --i1) {
#pragma ivdep
	for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	  bulkb[ih+ihmax][i1][i0] +=
	    sdiv[i1-gsc_p[1]+ih][i0-gsc_p[0]]*sdivbb[i1-gsc_p[1]][i0-gsc_p[0]];
	}
      }
    }
    for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
      for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	sdivb0[i1 - gsc_p[1]][i0 - gsc_p[0]] += 
	  bulk[i1][i0]*sdivbb[i1-gsc_p[1]][i0-gsc_p[0]];
      }
    }

    for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
      for (ioff = maxoff-1; ioff > -1; --ioff)
#pragma ivdep
	for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
	  tempb = c[0][ioff]*sdivb0[i1-gsc_p[1]][i0-gsc_p[0]];
	  tempb0 = c[1][ioff]*sdivb0[i1-gsc_p[1]][i0-gsc_p[0]];
	  v0b[i1][i0 + ioff] = v0b[i1][i0 + ioff] + tempb;
	  v0b[i1][i0 - ioff - 1] = v0b[i1][i0 - ioff - 1] - tempb;
	  v1b[i1 + ioff][i0] = v1b[i1 + ioff][i0] + tempb0;
	  v1b[i1 - ioff - 1][i0] = v1b[i1 - ioff - 1][i0] - tempb0;
	}
    }

    /*
      float x = 0.0f;
      for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
      for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
      x += fabs(bulkb[0][i1][i0]);
      }
      }
      fprintf(stderr,"x=%g\n",x);
    */
  }
}
