#!/bin/python
from rsf.proj import *

#   GENERATE TWO LAYER MODEL WITH DIPPING INTERFACE
Flow('layer_model',None,
    '''standardmodel model=2 choose=1
        d1=2 n1=201 d2=2 n2=301 d3=2 n3=301
        hfile=${TARGET}''',stdin=0,stdout=-1)
Flow('top_mask','layer_model',
    '''mask max=2.2 | scale dscale=1.0 |
        transp plane=12 | transp plane=23 |
        put label1="x" unit1="m" |
        put label2="y" unit2="m" |
        put label3="z" unit3="m" ''')
Flow('bottom_mask','layer_model',
    '''mask min=2.2 | scale dscale=1.0 |
        transp plane=12 | transp plane=23 |
        put label1="x" unit1="m" |
        put label2="y" unit2="m" |
        put label3="z" unit3="m" ''')

# rho(2.5~2.65)
Flow('rho',['top_mask','bottom_mask'],
    '''add ${SOURCES[0]} ${SOURCES[1]} scale=2.5,2.65''',stdin=0)
# vs(1~2)
Flow('vs',['top_mask','bottom_mask'],
    '''add ${SOURCES[0]} ${SOURCES[1]} scale=1,2''',stdin=0)
# vp(2~4)
Flow('vp',['top_mask','bottom_mask'],
    '''add ${SOURCES[0]} ${SOURCES[1]} scale=2,4''',stdin=0)

for file in ['rho','vp','vs']:
    Plot(file,file,'''window f2=125 n2=1 |
        sfgrey color=e scalebar=y title=\"%s\" '''%(file))

