#!/bin/python

import os

RSFROOT=os.getenv('RSFROOT')
RSFROOT_LIB=os.path.join(RSFROOT, 'lib')
RSFROOT_INC=os.path.join(RSFROOT, 'include')

env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'INTEL_LICENSE_FILE': os.environ['INTEL_LICENSE_FILE']})
env['CXX']='/opt/apps/intel/psxe_2017_u1/bin/icpc'
env['CXXFLAGS']=['-O3', '-qopenmp', '-restrict', '-std=c++14', '-xMIC-AVX512', '-qopt-report=4']
env['CPPPATH']=[RSFROOT_INC]
env['CPPDEFINES']=['NO_BLAS'] #because madagascar is compiled this way in stampede                                                                            
env['LIBS']=['rsf++','rsf', 'm']
env['LIBPATH']=[RSFROOT_LIB]
env['LINKFLAGS']=env['CXXFLAGS']


env.Program(target = 'main',
            source = Glob('*.cpp'))
