from rsf.tex import *

End(
use='amsmath,setspace,wasysym,graphicx,float,subfig,natbib',

include=r'''
\newcommand{\rs}[1]{\mathstrut\mbox{\scriptsize\rm \#1}}
\newcommand{\rr}[1]{\mbox{\rm #1}}
\newcommand{\mb}{\mathbf}
\newcommand{\om}{\bar{m}}
\newcommand{\oM}{\bar{M}}
\newcommand{\oF}{\bar{F}}
\newcommand{\cF}{\mathcal{F}}
\newcommand{\ocF}{\bar{\mathcal{F}}}
\newcommand{\cJ}{\mathcal{J}}
\newcommand{\bx}{{\bf x}}
\newcommand{\be}{\begin{equation}}
\newcommand{\ee}{\end{equation}}
\everymath{\displaystyle}
''',
color='ALL'
)





