" ",
  " ",
  " -------------------------------- CG and CGNE -------------------------------",
  " ",
  " conjugate gradient parameters",
  " rvl/umin/include/cgalg.hh, rvl/umin/include/cgnealg.hh",
  " ",                 
  " ---------------------------- begin cg parameters ---------------------------",
  " ",
  " ResidualTol = 100.0*numeric_limits<atype>::epsilon()",
  "   = relative stopping tolerance for residual norm decrease",
  " GradientTol = 100.0*numeric_limits<atype>::epsilon()",
  "   = relative stopping tolerance for normal residual decrease",
  " MaxIter = 10",
  "   = maximum permitted iterations",
  " MaxStep = numeric_limits<atype>::max()",
  "   = max step length (trust radius)",
  " ",
  " ------------------------------ end cg parameters ---------------------------",

