from rsf.tex import *

End(
lclass='georeport',
options='notimes',
use='natbib,graphicx,color,listings,amsmath,amssymb,amsbsy,float,wasysym,setspace,bm',
include=r'''
      \newcommand{\oF}{\bar{F}}
      \newcommand{\oS}{\bar{S}}
      \newcommand{\fl}{f_{\lambda}}
      \newcommand{\dl}{d_{\lambda}}
      \newcommand{\bx}{{\bf x}}
''')

