#!/bin/python
from rsf.proj import *



#   GENERATE 3D HOMOGENEOUS MODEL
Flow('base',None,
    '''spike d1=0.5 n1=289 d2=0.5 n2=289 d3=0.5 n3=385 mag=1 |
        put label1="x" unit1="m" |
        put label2="y" unit2="m" |
        put label3="z" unit3="m" ''',stdin=0)



# rho(2.5)
Flow('rho','base', "scale dscale=2.5")
# vs(1)
Flow('vs','base', "scale dscale=1")
# vp(2)
Flow('vp','base', "scale dscale=2")



for file in ['rho','vp','vs']:
    Plot(file,file,'''window f2=125 n2=1 |
        sfgrey color=e scalebar=y title=\"%s\" '''%(file))

