from rsf.tex import *

End(

options='georeport,12pt',

use='natbib,graphicx,color,amsmath,amsthm,amssymb,amsbsy,wasysym,setspace,bm,float,hyperref,algorithm,algpseudocode',

include=r'''
\newcommand{\mb}{\mathbf}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\bk}{\mathbf{k}}
\newcommand{\bv}{\mathbf{v}}
\newcommand{\bu}{\mathbf{u}}
\newcommand{\by}{\mathbf{y}}
\newcommand{\bz}{\mathbf{z}}
\newcommand{\bh}{\mathbf{h}}
\newcommand{\bR}{\mathbf{R}}
\newcommand{\oS}{\bar{S}}
\newcommand{\of}{\bar{f}}
\newcommand{\ofa}{\bar{f}_{\alpha,\lambda}}
\newcommand{\oNa}{\bar{N}_{\alpha}}
\newcommand{\Ja}{J_{\alpha}}
\newcommand{\Jz}{J_{0,\sigma}}
\newcommand{\Ml}{M + \lambda^2I}
\newcommand{\Mld}{M_{\lambda}^{\dagger}}
\newcommand{\ua}{u_{\alpha}}
\newcommand{\va}{v_{\alpha}}
\newcommand{\uz}{u_0}
\newcommand{\tJa}{\tilde{J}_{\alpha}}
\newcommand{\tJz}{\tilde{J}_{0}}
\newcommand{\wl}{w_{\lambda}}
\newcommand{\fl}{f_{\lambda}}
\newcommand{\Fl}{F_{\lambda}}
\newcommand{\Fla}{F^0_{\lambda}}
\newcommand{\Flb}{F^1_{\lambda}}
\newcommand{\Sl}{S_{\lambda}}
\newcommand{\Sla}{S^0_{\lambda}}
\newcommand{\Slb}{S^1_{\lambda}}
\newcommand{\dl}{d_{\lambda}}
\newcommand{\dzl}{d^0_{\lambda}}
\newcommand{\dla}{d^0_{\lambda}}
\newcommand{\dlb}{d^1_{\lambda}}
\newcommand{\Ol}{O(\lambda)}
\newcommand{\fwl}{\hat{w}_{\lambda}}
\newcommand{\ul}{u_{\lambda}}
\newcommand{\uzl}{u^0_{\lambda}}
\newcommand{\fu}{\hat{u}}
\newcommand{\fuzs}{\hat{u}^0_{\sigma}}
\newcommand{\ful}{\hat{u}_{\lambda}}
\newcommand{\fuzl}{\hat{u}^0_{\lambda}}
\newtheorem{lemma}{Lemma}
\newtheorem{theorem}{Theorem}
\newtheorem{prop}{Proposition}
\newtheorem{alg}{Algorithm}
\newtheorem{remark}{Remark}
\newtheorem{cor}{Corollary}
\newtheorem{example}{Example}
\newtheorem{definition}{Defenition}

''',
color='ALL'
)





