from rsf.proj import *
from trip.proj import getnum
import os

################################# DEFNS ##################################
CWPROOT         = os.getenv('CWPROOT')
sunull          = os.path.join(CWPROOT,'bin/sunull')
sushw           = os.path.join(CWPROOT,'bin/sushw')
suchw           = os.path.join(CWPROOT,'bin/suchw')
sugain          = os.path.join(CWPROOT,'bin/sugain')
suwind          = os.path.join(CWPROOT,'bin/suwind')
suwaveform      = os.path.join(CWPROOT,'bin/suwaveform')
supsimage       = os.path.join(CWPROOT,'bin/supsimage')
suspike         = os.path.join(CWPROOT,'bin/suspike')
sufilter        = os.path.join(CWPROOT,'bin/sufilter')
suconv          = os.path.join(CWPROOT,'bin/suconv')
sucddecon       = os.path.join(CWPROOT,'bin/sucddecon')
sufrac          = os.path.join(CWPROOT,'bin/sufrac')
sustack         = os.path.join(CWPROOT,'bin/sustack')
suop            = os.path.join(CWPROOT,'bin/suop')
sugain          = os.path.join(CWPROOT,'bin/sugain')
sumax           = os.path.join(CWPROOT,'bin/sumax')
suop2           = os.path.join(CWPROOT,'bin/suop2')
suflip          = os.path.join(CWPROOT,'bin/suflip')
sutxtaper       = os.path.join(CWPROOT,'bin/sutxtaper')
a2b             = os.path.join(CWPROOT,'bin/a2b')
suresamp        = os.path.join(CWPROOT,'bin/suresamp')
suamp           = os.path.join(CWPROOT,'bin/suamp')
sufft           = os.path.join(CWPROOT,'bin/sufft')
sushift         = os.path.join(CWPROOT,'bin/sushift')
MYAPPS          = os.getenv('MYAPPS')
asg             = os.path.join(MYAPPS,'trip/iwave/asg/main/sim.x')
asg0cgne        = os.path.join(MYAPPS,'trip/iwave/asg/main/sse.x')
asgfwi          = os.path.join(MYAPPS,'trip/iwave/asg/main/fwi.x')
deriv           = os.path.join(MYAPPS,'trip/iwave/trace/main/SEGYDeriv.x')
tscale          = os.path.join(MYAPPS,'trip/iwave/trace/main/SEGYTraceScale.x')
#######################################################################

TMIN = 1.8
TMAX = 2.8

##################################### data from data ##########################

BASIC='../data'

# build list of data to import
SRCLIST=[]
#for i in range(3):
for i in range(1):
    SRCLIST.append('bmh'+str(i)+'.rsf')
    SRCLIST.append('byh'+str(i)+'.rsf')
    SRCLIST.append('bmw'+str(i)+'.rsf')
    SRCLIST.append('bml'+str(i)+'.rsf')
    SRCLIST.append('bmt'+str(i)+'.rsf')    
    SRCLIST.append('ptph'+str(i)+'.su')
    SRCLIST.append('ptpw'+str(i)+'.su')
    SRCLIST.append('ptpl'+str(i)+'.su')
    SRCLIST.append('ptpt'+str(i)+'.su')
    SRCLIST.append('pulse0'+str(i)+'.su')        
    for j in range(4):
    	SRCLIST.append('ptsrc'+str(j)+str(i)+'.su')
    SRCLIST.append('plbulksm'+str(i)+'.rsf')
    SRCLIST.append('dwdata'+str(i)+'.su')
    SRCLIST.append('dwraw'+str(i)+'.su')
    SRCLIST.append('ndwdata'+str(i)+'.su')
    SRCLIST.append('ndwraw'+str(i)+'.su')
    SRCLIST.append('ndwmute'+str(i)+'.su')
    SRCLIST.append('plrays'+str(i)+'.rsf')
    SRCLIST.append('plraysdwp'+str(i)+'.rsf')
    SRCLIST.append('plraysdwm'+str(i)+'.rsf')
    SRCLIST.append('plraysdw'+str(i)+'.rsf')    
    SRCLIST.append('plraysndpnh'+str(i)+'.rsf')
    SRCLIST.append('xtraysendfiner1interp' + str(i) + '.rsf')
    SRCLIST.append('xtraysendfiner2interp' + str(i) + '.rsf')    
    

if not os.path.exists(BASIC):
    print('cannot find data source directory ' + BASIC)
    Exit(1)
else:
    for i in SRCLIST:
        SRC = os.path.join(BASIC,i)
        if not os.path.exists(SRC):
            print('you must build the target ' + SRC)
            print('before building this project') 
            Exit(1)
        Flow(i,SRC,'/bin/cp ' + SRC + ' ' + i, stdin=0, stdout=-1)

dx=20
ox=2000

Flow('pulse00','pulse00.su','suread read=data endian=0 ')
Result('pulse00', 'wiggle clip=500.0 poly=y transp=y xinch=4 yinch=8 wanttitle=n label2=""')
Flow('ptsrc00','ptsrc00.su',
     'suread read=data endian=0 | put d2=20 o2=1500 | pad n2=226| window min2=2000 max2=6000') 
Result('ptsrc00','grey color=j scalebar=y label2=Position unit2=m ' +
           'barlabel=GPa wanttitle=n xinch=10 yinch=5 clip=300 minval=-300 maxval=300')

for i in ['h', 'w', 'l', 't']: 
    Result('bm' + i + '0',
           'grey color=j scalebar=y minval=1.5 maxval=5 bias=4.0 wanttitle=n ' +
	   'label1="Depth" unit1=m label2="Position" unit2=m barlabel=GPa ' +
	   'xinch=10 yinch=5')
    Flow('ptpwind' + i + '0.su', 'ptp' + i + '0.su',
         suwind + ' tmin=' + str(TMIN) + ' tmax=' + str(TMAX)) 
    Flow('ptpwind' + i + '0','ptpwind' + i + '0.su',
         'suread read=data endian=0 | put d2=' + str(dx) + ' o2=' + str(ox)) 
    Result('ptpwind' + i + '0','grey color=j scalebar=y label2=Position unit2=m ' +
           'barlabel=GPa wanttitle=n xinch=10 yinch=5 clip=0.15 minval=-0.15 maxval=0.15')



#diving wave plots

Result('plbulksm0',
       'grey color=j scalebar=y minval=4 maxval=36 bias=4.0 wanttitle=n ' +
       'label1="Depth" unit1=m label2="Position" unit2=m barlabel=GPa ' +
       'xinch=10 yinch=5')
Flow('dwdata0','../data/dwdata0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('dwdata0','grey color=j scalebar=y label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=10 yinch=5 clip=0.15 minval=-0.15 maxval=0.15')    
Flow('dwraw0','../data/dwraw0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('dwraw0','grey color=j scalebar=y label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=10 yinch=5 clip=0.15 minval=-0.15 maxval=0.15')

Flow('ndwdata0','../data/ndwdata0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwdata0','grey color=j scalebar=n label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=5 yinch=5 clip=0.02 ' +
     'minval=-0.1 maxval=0.1 min2=10000')
Flow('ndwdatavz0','../diving/ndwdatavz0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwdatavz0','grey color=j scalebar=n label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=5 yinch=5 clip=0.02 ' +
     'minval=-0.02 maxval=0.02 min2=14000')
Flow('ndwdataresrcplbulksm0','../diving/ndwdataresrcplbulksm0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwdataresrcplbulksm0','grey color=j scalebar=n label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=5 yinch=5 clip=5.0 ' +
     'minval=-5.0 maxval=5.0 min1=-0.5 max1=1.5 min2=5000 max2=15000')
Flow('ndwdataresimplbulksm0','../diving/ndwdataresimplbulksm0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwdataresimplbulksm0','grey color=j scalebar=n label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=5 yinch=5 clip=0.02 ' +
     'minval=-0.02 maxval=0.02 min2=14000')
Flow('ndwdatarediffplbulksm0','../diving/ndwdatarediffplbulksm0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwdatarediffplbulksm0','grey color=j scalebar=n label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=5 yinch=5 clip=0.02 ' +
     'minval=-0.02 maxval=0.02 min2=14000')

Flow('ndwraw0','../data/ndwraw0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwraw0','grey color=j scalebar=n label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=5 yinch=5 clip=0.1 ' +
     'minval=-0.1 maxval=0.1 min2=10000')
Flow('ndwmute0','../data/ndwmute0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('ndwmute0','grey color=j scalebar=y label2=Position unit2=m min2=10000' +
     'barlabel="" wanttitle=n xinch=8 yinch=8 clip=1 minval=0 maxval=1')     
Flow('dwsrc0','../data/dwsrc0.su',
     'suread read=data endian=0 | put d2=' + str(dx) + ' o2=0')
Result('dwsrc0','grey color=j scalebar=y label2=Position unit2=m ' +
     'barlabel=GPa wanttitle=n xinch=10 yinch=5 clip=0.15 minval=-0.15 maxval=0.15')

Plot('plbulksm0',
     'grey color=j scalebar=y minval=4 maxval=36 bias=4.0 wanttitle=n ' +
     'label1="Depth" unit1=m label2="Position" unit2=m ' +
     'min2=0 max2=20000 xinch=10 yinch=5 xll=2.5')
     
Plot('plrays0','graph transp=y yreverse=y plotcol=5 wanttitle=n wantaxis=n ' +
     'min2=0 max2=20000 label1="" label2="" unit1="" unit2="" ' +
     'xinch=8.85 yinch=5.0 xll=2.34 yll=2.65')

Plot('plraysndpnh0','graph transp=y yreverse=y plotcol=5 wanttitle=n wantaxis=n ' +
     'min1=0 max1=4000 min2=0 max2=20000 label1="" label2="" unit1="" unit2="" ' +
     'xinch=8.85 yinch=5.0 xll=2.33 yll=2.62')

Plot('plraysdwp0','graph transp=y yreverse=y plotcol=6 wanttitle=n wantaxis=n ' +
     'min1=0 max1=4000 min2=0 max2=20000 label1="" label2="" unit1="" unit2="" ' +
     'xinch=8.85 yinch=5.0 xll=2.34 yll=2.65')
Plot('plraysdwm0','graph transp=y yreverse=y plotcol=6 wanttitle=n wantaxis=n ' +
     'min1=0 max1=4000 min2=0 max2=20000 label1="" label2="" unit1="" unit2="" ' +
     'xinch=8.85 yinch=5.0 xll=2.34 yll=2.65')
Plot('plraysdw0','graph transp=y yreverse=y plotcol=6 wanttitle=n wantaxis=n ' +
     'min1=0 max1=4000 min2=0 max2=20000 label1="" label2="" unit1="" unit2="" ' +
     'xinch=8.85 yinch=5.0 xll=2.33 yll=2.62')

Plot('oplrays0', ['plbulksm0', 'plraysndpnh0'], 'Overlay')

#     'xinch=10 yinch=5)
#     +
#    'xinch=8.85 yinch=5.07 xll=2.34 yll=2.65')
     
#'xinch=10 yinch=5'

Result('ooplrays0',['oplrays0', 'plraysdw0'], 'Overlay')

Flow('xtraydirect',None, 'math n1=501 d1=20 o1=10000 output=\'0.5*sqrt((x1-10000)^2+250000)\'', stdin=0)

Plot('xtraydirect','graph plotcol=7 min1=10000 max1=20000 min2=0 max2=5000 wanttitle=n wantaxis=y label1=Offset unit1=m label2=Time unit2=ms plotfat=4 yreverse=y')
Plot('xtraysendfiner1interp0','graph plotcol=6 min1=10000 max1=20000 min2=0 max2=5000 wanttitle=n wantaxis=n plotfat=7 yreverse=y')
Plot('xtraysendfiner2interp0','graph plotcol=5 min1=10000 max1=20000 min2=0 max2=5000 wanttitle=n wantaxis=n plotfat=7 yreverse=y')

Plot('oxtraysend',['xtraysendfiner1interp0','xtraysendfiner2interp0'], 'Overlay')
Result('ooxtraysend',['oxtraysend','xtraydirect'], 'Overlay')

Result('xtraydirect','graph plotcol=7 min1=10000 max1=20000 min2=0 max2=5000 wanttitle=n wantaxis=y label1=Offset unit1=m label2=Time unit2=ms plotfat=7')

End()
