  " ",
  " ----------------------------- SEGYTAPERMUTE --------------------------------",
  " ",
    " Linear top mute with cubic taper, cubic taper on offset or gx, ",
  " zero-slope bottom mute with cubic taper.",
  " iwave/trace/include/segyops.hh",
  " ",
  " ----------------------------- begin segytapermute -------------------------",
  " ",
    " Mute parameters:",
    " mute_slope   = 0.0         slowness, ms/m",
    " mute_zotime  = 0.0         zero offset intercept, ms",
    " mute_width   = 0.0         width of mute taper, ms",
    " mute_type    = 0           x coord used: 0: offset, 1: gx, m",
  " ",
    " Taper parameters: piecewise cubic taper on any number of header keys.",
    " for each key, location of four corner values given. Syntax:",
    "   key:low_cut,low_pass,high_pass,high_cut",
    " combine tapers on key1, key2,... axes by concatenating with semi-colon",
    " separator:",
    "   key1:lc1,lp1,hp1,hc1;key2:lc2,lp2,hp2,hc2;...",
    " keyword for invoking taper is taperpars:",
    "   taperpars=<string of above form>",
    " default is no taper",
    " ",
  " ------------------------------ end segytapermute ---------------------------",
