" ---------------------------------- base params ----------------------------",
  " ",
  " Base parameters are strings, each defining a relative or absolute path",
  " to a file. These files provide the geometry (grids, sensor positions, etc.)",
  " that forms the characteristic metadata for domain and range spaces of the",
  " simulation operator. Also, data associated with or contained in these files",
  " initializes the corresponding fields (for input parameters). ",
  " ",
  " Domain and range spaces are Cartesian products of one or more ",
  " factor spaces defined by individual files. The list provided in the next ",
  " doc section may enumerate more base parameters than are actually required",
  " to define a simulator of the intended type; in that case, feasible",
  " subsets are specified.",
  " ",
  " Conventional terminology divides base parameters into three classes:",
  "    model parameters  - inputs to base case simulation, having nonlinear",
  "                        influence on outputs, typically appearing as ",
  "                        coefficient fields in equations of motion",
  "    source parameters - inputs to base case simulation, having linear",
  "                        influence on outputs, typically appearing as ",
  "                        right-hand side fields in equations of motion",
  "    data parameters   - outputs of base case simulation",
  " ",
  " The domain space of the simulator is thus a cartesian product: ",
  "          [model parameters] x [source parameters]",
  " and the action is linear in the second factor. Each factor is in turn ",
  " a cartesian product."
  " ",
" ---------------------------------- base params ----------------------------",  
