" --------------------------- deriv params -------------------------------",
  " ",
  " Mapping Selection:",
  " ",
  "          deriv = 0           order of derivative of forward map to compute",
  "        adjoint = 0           0: forward, 1: adjoint  ",
  " ",
  " Use cases: ",
  " ",
  " deriv = 0",
  "   adjoint = 0: base simulator",
  "   adjoint = 1: adjoint of linear operator on source params, for fixed",
  "                model params as given in base param list. Source params",
  "                = output, data params = input",
  " ",
  " deriv = 1",
  "   adjoint = 0: fwd deriv. For each model param with keyword",
  "                xxx, add keyword xxx_d1, with value = path to file storing",
  "                input perturbation data for parameter indicated by xxx. Output",
  "                keyed by data parameter keywords.",
  "   adjoint = 1: adj deriv. For each model param with keyword xxx,",
  "                add keyword xxx_b1, with value = path to file storing",
  "                output perturbation data for parameter indicated by xxx.",
  "                Data parameters become input.",
  " ",
  " deriv = 2",
  "   adjoint = 0: fwd 2nd deriv (bilinear). For each model param with keyword",
  "                xxx, add keywords xxx_d1 and xxx_d2, with values = paths",
  "                to files storing input perturbation data for parameter ",
  "                indicated by xxx. Output keyed by data parameter keywords.",
  "   adjoint = 1: adj 2nd deriv = adjoint of linear op obtained by fixing",
  "                first component of input pair for bilinear forward op.",
  "                For each model param with keyword xxx, add keyword xxx_d1",
  "                value = path to file storing first component (input), and",
  "                xxx_b2, value = path to file storing second component ",
  "                (output). Data parameters become input.",
  " ",
  " Notes on file preparation:",
  " ",
  " Input Data -",
  " ",
  "   Traces (SEGY/SU format, suffix .su), are interpreted as arrays of point",
  "   sources with  position(s) indicated by RECEIVER coordinates (gx, gy, ",
  "   gelev) - prepare input source with correct headers using SU utilities or",
  "   utilities such as trace/main/towed_array.x. For adjoint simulation, traces",
  "   output by earlier simulations or with the same header data are already in ",
  "   correct format for input.", 
  " ",
  "   Spatial fields (RSF format, suffix .rsf) interpreted must have time axis ",
  "   specified by non-standard header id[dim+1] = dim, for example for 2D ",
  "   simulation, id3=2. Time sample points identified by corresponding axis: ",
  "   in 2D first frame is o3, frame interval d3, number of frames is n3. ",
  "   Special case: one frame, origin and interval defaulted - interpreted",
  "   as initial Cauchy data, with time origin determined by output trace data. ",
  " ",
  "   Spatial fields must be specified on grid commensurable with computational",
  "   grid.",
  " ",
  " Output Data - ",
  " ",
  "   Some, or all of the following options may be specified.",
  " ",
  "   Traces are stored in SU format, with the trace headers having the normal role",
  "   of specifying acquisition geometry.",
  " ",
  "   Movies stored in RSF format, identified by the nonstandard parameter",
  "   id[dim+1]=dim, in a mirror-image role to Cauchy source data.",
  " ",
  " Note that all files participating in a simulation, including output files,",
  " must exist and possess correct metadata (headers) prior to execution.",
  " ",
  " NOTE: at least one fwd output file (trace or movie) must be specified.",
  " ",
  " --------------------------- i/o parameters -------------------------------",
