" ---------------------------- fd parameters -----------------------------",
  " FD info:",
  " ",
  "          order = 2           spatial half-order",
  "            cfl = 0.75        proportion of max dt/dx",
  "           cmin = 1.0         min permitted velocity (m/ms) - sanity check",
  "           cmax = 4.5         max permitted velocity (m/ms) - used in dt comp",
  "           dmin = 0.8         min permitted density (g/cm^3) - sanity check",
  "           dmax = 3.0         min permitted density (g/cm^3) - sanity check",
  " ",
  "         nsnaps = 0           number of checkpoints for adjoint ",
  "                              state checkpointing scheme",
  "        sampord = 1           spatial interp order for sampling or adjoint",
  "                              sampling trace data to/from grid - 0 (nr nbr) ",
  "                              or 1 (multilin)",  
  " ",
  " ---------------------------- fd parameters -----------------------------",
