" ---------------------------- IWAVE INVERSION -------------------------------",
  " ",
  " IWAVE based inversions include full waveform inversion (fwi), linear ",
  " inversion (lin), and variable projection inversion for simultaneous ",
  " determination of linear and nonlinear model parameters (vpm). All three",
  " share a common user interface, and collaborate with various wave physics",
  " simulators. Along with many controls on optimization and simulation, the",
  " inversion commands permit the user to chose which parameter fields to ",
  " invert, amongst those participating in each type of wave physics."
  " ",
  " Selection of inversion parameters used the keys that select simulation parameters.",
  " The IOKEYS struct specifies these keys, along with an active tag that takes three",
  " values: 0 for inactive input/output (i.e. not participating in any inversion), 1 for",
  " active and presumed to have a nonlinear influence on the data (or a nonlinear",
  " function of the inputs), such as a velocity or stiffness field,  and 2 for active",
  " and presumed to be a linear input or output, such as a source field or linearly",
  " sampled data field. To invert for a parameter corresponding ",
  " to an active input key foo, add the key foo_est to the command argument list,",
  " with value equal to the filename under which the inverted foo data is to be stored.",
  " For example, to carry out Born inversion (Least Squares Migration) with constant",
  " density acoustic modeling as implemented in the acd package, add csq_est=<path>",
  " to the argument list, where <path> is the path to the file storing the",
  " inverted squared velocity perturbation. Supply this along with other arguments as",
  " described in the self-doc to acdlin. Remember that all output files must also have",
  " been initialized, with correct metadata, before use.",
  " ",
  " Note that the same key=value pair, supplied to acdfwi instead, along with",
  " appropriate other parameters, results in nonlinear (full waveform) inversion",
  " rather than linear inversion for the corresponding material parameter field.",
  " Same info to acdvpm, along with appropriate keys for one or more source fields ",
  " and other appropriate parameters, results in simultaneous inversion for material",
  " parameters (coefficients in the wave equation) and source parameters. The same",
  " goes for other wave physics specializations of IWAVE inversion.",
  " ",
  " Note also that if you do not supply an _est key for a material parameter field ",
  " listed as active in the IOKEYS struct, then IWAVE treats the corresponding",
  " parameter as fixed and does not update it during the inversion. For example,",
  " to perform inversion for the bulk modulus without changing the density (either ",
  " linear (Born) or nonlinear (FWI)) using the acoustic staggered grid (asg) model,",
  " include bulkmod_est but NOT buoyancy_est in your parameter list.",
  " ",
  " The linear drivers xxxlin perform both Born (linearized) inversion (aka Least",
  " Squares Migration) if _est is added to a material parameter key, or inversion",
  " for source (linear parameters), if _est is added to source keys. For instance",
  " if source_est=... appears in the parameter list for acdlin, then a set of source",
  " traces is estimated, having the same geometry as the data specified by source=.... ",
  " ",
  " For linear inversion (drivers xxxsli), either coefficient perturbations (eg. ",
  " bulkmod_est) or source updates, (eg. source_p_est) may be requested, but not",
  " both - to estimate both is a nonlinear problem for which a VPM driver (xxxvpm)",
  " should be used.",
  " ",
  " ---------------------------- IWAVE INVERSION -------------------------------",
  " ",
