#ifndef __USAGE_SELFDOC__
#define __USAGE_SELFDOC__
" ",
" --------------------------------- usage ----------------------------------",
  " ",
  " Invoke single threaded execution by ",
  " ",
  " <path to this command> [key=value list] ",
  " ",
  " or parallel execution via interactive or batch MPI using appropriate ",
  " MPI invocation. For parallel execution, code must be compiled with ",
  " flag -DIWAVE_USE_MPI.",
  " ",
  " Required parameter, keyword = key:  ",
  "            key = <type>*",
  " Optional parameter, keyword = key:",
  "            key = <type>",
  " Given values used as default. Any parameter with default value",
  " given is a priori a required parameter. IWAVE parameter reader",
  " disregards white space, so \"key=value\", \"key = value\", etc.",
  " have same effect.",
  " ",
  " --------------------------------- usage ----------------------------------",
#endif
