#!/bin/python
from rsf.proj import *



#   GENERATE 3D HOMOGENEOUS MODEL
Flow('base',None,
    '''spike d1=1 n1=301 d2=1 n2=301 d3=1 n3=201 mag=1 |
        put label1="x" unit1="m" |
        put label2="y" unit2="m" |
        put label3="z" unit3="m" ''',stdin=0)



# rho(2.5)
Flow('rho','base',"scale dscale=2.5")
# vs(1)
Flow('vs','base', "scale dscale=1")
# vp(2)
Flow('vp','base',"scale dscale=2")



for file in ['rho','vp','vs']:
    Plot(file,file,'''window f2=125 n2=1 |
        sfgrey color=e scalebar=y title=\"%s\" '''%(file))

