/*        Generated by TAPENADE     (INRIA, Ecuador team)
	  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/
/*
  Differentiation of asg2dtap in forward (tangent) mode:
  variations   of useful results: **v0 **v1 **p0 **p1
  with respect to varying inputs: **v0 **v1 ***bulk **buoy **p0
  **p1
  RW status of diff variables: **v0:in-out **v1:in-out ***bulk:in
  **buoy:in **p0:in-out **p1:in-out
  Plus diff mem management of: v0:in *v0:in v1:in *v1:in bulk:in
  *bulk:in **bulk:in buoy:in *buoy:in p0:in *p0:in
  p1:in *p1:in sdiv:in *sdiv:in sdivb:in *sdivb:in
  gradp0:in gradp1:in
*/

#include "cstd.h"

void asg2dtap_d(float *** restrict bulk, float *** restrict bulkd,
		float ** restrict buoy, float ** restrict buoyd,
		float ** restrict p0, float **  restrict p0d,
		float ** restrict p1, float ** restrict p1d,
		float ** restrict v0, float ** restrict v0d,
		float ** restrict v1, float ** restrict v1d,
		float ** restrict ep, float ** restrict epp,
		float ** restrict ev, float ** restrict evp,
		float ** restrict sdiv, float ** restrict sdivd,
		float ** restrict sdivb, float ** restrict sdivbd,
		float *gradp0, float *gradp0d,
		float *gradp1, float *gradp1d,
		int *gsc_p, int *gec_p,
		int *gsc_v0, int *gec_v0,
		int *gsc_v1, int *gec_v1,
		int *lbc, int *rbc,
		float dh, int ihmax,
		int maxoff, float ** restrict c,
		FILE * stream) {
  int i0, i1;
  int ioff;
  {
    int ih;
    int sh;
    int eh;
    //    fprintf(stderr,"1\n");
    for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
      memset((char *)(sdiv[i1-gsc_p[1]]),  0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      memset((char *)(sdivb[i1-gsc_p[1]]), 0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      memset((char *)(sdivd[i1-gsc_p[1]]),  0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      memset((char *)(sdivbd[i1-gsc_p[1]]), 0, (gec_p[0]-gsc_p[0]+1)*sizeof(float));
      /*
	for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	sdivd[i1 - gsc_p[1]][i0 - gsc_p[0]] = 0.0;
	sdiv[i1 - gsc_p[1]][i0 - gsc_p[0]] = 0.0f;
	sdivbd[i1 - gsc_p[1]][i0 - gsc_p[0]] = 0.0;
	sdivb[i1 - gsc_p[1]][i0 - gsc_p[0]] = 0.0f;
	}
      */
      //      fprintf(stderr,"1b\n");      
      for (ioff = 0; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	  sdivd[i1 - gsc_p[1]][i0 - gsc_p[0]] = sdivd[i1 - gsc_p[1]][i0 - gsc_p[0]] + c[0][ioff]*(v0d[i1][i0+ioff]-v0d[i1][i0-ioff-1]) + c[1][ioff]*(v1d[i1+ioff][i0]-v1d[i1-ioff-1][i0]);
	  sdiv[i1 - gsc_p[1]][i0 - gsc_p[0]] += c[0][ioff]*(v0[i1][i0+ioff]-v0[i1][i0-ioff-1]) + c[1][ioff]*(v1[i1+ioff][i0]-v1[i1-ioff-1][i0]);
	}
    }
    //    **sdivbd = 0.0;
    //    fprintf(stderr,"2\n");    
    for (ih = -ihmax; ih < ihmax+1; ++ih) {
      //      sh = ((ih <= 0) ?  gsc_p[1]-ih : gsc_p[1]);
      //      eh = ((ih >= 0) ?  gec_p[1]-ih : gec_p[1]);
      if (ih <=0) {
	sh = gsc_p[1]; eh = gec_p[1] + 2*ih;
      }
      else {
	sh = gsc_p[1] + 2*ih; eh = gec_p[1];
      }
      for (i1 = sh; i1 < eh+1; ++i1)
#pragma ivdep
	for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	  sdivbd[i1 - gsc_p[1]][i0 - gsc_p[0]] +=
	    dh*(bulkd[ih+ihmax][i1-ih][i0]*sdiv[i1-gsc_p[1]-2*ih][i0-gsc_p[0]] +
		bulk[ih+ihmax][i1-ih][i0]*sdivd[i1-gsc_p[1]-2*ih][i0-gsc_p[0]]);
	  sdivb[i1 - gsc_p[1]][i0 - gsc_p[0]] +=
	    dh*bulk[ih+ihmax][i1-ih][i0]*sdiv[i1-gsc_p[1]-2*ih][i0-gsc_p[0]];
	}
    }
    //    fprintf(stderr,"3\n");
    for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1)
#pragma ivdep
      for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	p0d[i1][i0] = epp[0][i0]*(ep[0][i0]*p0d[i1][i0]-sdivbd[i1-gsc_p[
									1]][i0-gsc_p[0]]);
	p0[i1][i0] = (ep[0][i0]*p0[i1][i0]-sdivb[i1-gsc_p[1]][i0-gsc_p[0
								       ]])*epp[0][i0];
	p1d[i1][i0] = epp[1][i1]*(ep[1][i1]*p1d[i1][i0]-sdivbd[i1-gsc_p[
									1]][i0-gsc_p[0]]);
	p1[i1][i0] = (ep[1][i1]*p1[i1][i0]-sdivb[i1-gsc_p[1]][i0-gsc_p[0
								       ]])*epp[1][i1];
      }
    if (lbc[0])
      for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
	p0d[i1][gsc_p[0] - 1] = 0.0;
	p0[i1][gsc_p[0] - 1] = 0.0f;
	for (ioff = 1; ioff < maxoff; ++ioff) {
	  p0d[i1][gsc_p[0] - ioff - 1] = -p0d[i1][gsc_p[0]+ioff-1];
	  p0[i1][gsc_p[0] - ioff - 1] = -p0[i1][gsc_p[0]+ioff-1];
	}
      }
    if (rbc[0])
      for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
	p0d[i1][gec_p[0] + 1] = 0.0;
	p0[i1][gec_p[0] + 1] = 0.0f;
	for (ioff = 1; ioff < maxoff; ++ioff) {
	  p0d[i1][gec_p[0] + ioff + 1] = -p0d[i1][gec_p[0]-ioff+1];
	  p0[i1][gec_p[0] + ioff + 1] = -p0[i1][gec_p[0]-ioff+1];
	}
      }
    if (lbc[1])
#pragma ivdep
      for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	p1d[gsc_p[1] - 1][i0] = 0.0;
	p1[gsc_p[1] - 1][i0] = 0.0f;
	for (ioff = 1; ioff < maxoff; ++ioff) {
	  p1d[gsc_p[1] - ioff - 1][i0] = -p1d[gsc_p[1]+ioff-1][i0];
	  p1[gsc_p[1] - ioff - 1][i0] = -p1[gsc_p[1]+ioff-1][i0];
	}
      }
    if (rbc[1]) {
#pragma ivdep
      for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
	p1d[gec_p[1] + 1][i0] = 0.0;
	p1[gec_p[1] + 1][i0] = 0.0f;
	for (ioff = 1; ioff < maxoff; ++ioff) {
	  p1d[gec_p[1] + ioff + 1][i0] = -p1d[gec_p[1]-ioff+1][i0];
	  p1[gec_p[1] + ioff + 1][i0] = -p1[gec_p[1]-ioff+1][i0];
	}
      }
    }

    for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1) {
      memset((char *)gradp0, 0, (gec_v0[0]-gsc_v0[0]+1)*sizeof(float));
      memset((char *)gradp0d, 0, (gec_v0[0]-gsc_v0[0]+1)*sizeof(float));
      for (ioff = 0; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
	  gradp0d[i0 - gsc_v0[0]] = gradp0d[i0 - gsc_v0[0]] + c[0][
								   ioff]*(p0d[i1][i0+ioff+1]-p0d[i1][i0-ioff]);
	  gradp0[i0 - gsc_v0[0]] += c[0][ioff]*(p0[i1][i0+ioff+1]-p0[
								     i1][i0-ioff]);
	}
#pragma ivdep      
      for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
	v0d[i1][i0] = evp[0][i0]*(ev[0][i0]*v0d[i1][i0]-0.5f*((buoyd[i1]
							       [i0]+buoyd[i1][i0+1])*gradp0[i0-gsc_v0[0]]+(buoy[i1][i0]+
													   buoy[i1][i0+1])*gradp0d[i0-gsc_v0[0]]));
	v0[i1][i0] = evp[0][i0]*(ev[0][i0]*v0[i1][i0]-0.5f*(buoy[i1][i0]
							    +buoy[i1][i0+1])*gradp0[i0-gsc_v0[0]]);
      }
    }
    //    *gradp1d = 0.0;
    for (i1 = gsc_v1[1]; i1 < gec_v1[1]+1; ++i1) {
      memset((char *)gradp1, 0, (gec_v1[0]-gsc_v1[0]+1)*sizeof(float));
      memset((char *)gradp1d, 0, (gec_v1[0]-gsc_v1[0]+1)*sizeof(float));
      for (ioff = 0; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
	  gradp1d[i0 - gsc_v1[0]] = gradp1d[i0 - gsc_v1[0]] + c[1][
								   ioff]*(p1d[i1+ioff+1][i0]-p1d[i1-ioff][i0]);
	  gradp1[i0 - gsc_v1[0]] += c[1][ioff]*(p1[i1+ioff+1][i0]-p1[
								     i1-ioff][i0]);
	}
#pragma ivdep      
      for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
	v1d[i1][i0] = evp[1][i1]*(ev[1][i1]*v1d[i1][i0]-0.5f*((buoyd[i1]
							       [i0]+buoyd[i1+1][i0])*gradp1[i0-gsc_v1[0]]+(buoy[i1][i0]+
													   buoy[i1+1][i0])*gradp1d[i0-gsc_v1[0]]));
	v1[i1][i0] = evp[1][i1]*(ev[1][i1]*v1[i1][i0]-0.5f*(buoy[i1][i0]
							    +buoy[i1+1][i0])*gradp1[i0-gsc_v1[0]]);
      }
    }
    if (lbc[0])
      for (ioff = 1; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1) {
	  v0d[i1][gsc_v0[0] - ioff] = v0d[i1][gsc_v0[0] + ioff - 1];
	  v0[i1][gsc_v0[0] - ioff] = v0[i1][gsc_v0[0] + ioff - 1];
	}
    if (rbc[0])
      for (ioff = 1; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1) {
	  v0d[i1][gec_v0[0] + ioff] = v0d[i1][gec_v0[0] - ioff + 1];
	  v0[i1][gec_v0[0] + ioff] = v0[i1][gec_v0[0] - ioff + 1];
	}
    if (lbc[1])
      for (ioff = 1; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
	  v1d[gsc_v1[1] - ioff][i0] = v1d[gsc_v1[1] + ioff - 1][i0];
	  v1[gsc_v1[1] - ioff][i0] = v1[gsc_v1[1] + ioff - 1][i0];
	}
    if (rbc[1])
      for (ioff = 1; ioff < maxoff; ++ioff)
#pragma ivdep
	for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
	  v1d[gec_v1[1] + ioff][i0] = v1d[gec_v1[1] - ioff + 1][i0];
	  v1[gec_v1[1] + ioff][i0] = v1[gec_v1[1] - ioff + 1][i0];
	}
  }
}
