CC = 'mpicc' 
CCFLAGS = '-O3 -mfpmath=sse -ffast-math -fstrict-aliasing -ftree-vectorize --param vect-max-version-for-alias-checks=200 -pedantic -Wunused -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DIWAVE_USE_MPI'
CFLAGS = '-std=c99 -Wimplicit'
CXXFLAGS = '-std=c++11'
CXX = 'mpicxx'
