from rsf.tex import *

Paper('response',
lclass='georeport',
options='notimes',
use='hyperref,natbib,graphicx,color,listings,amsmath,amsthm,amssymb,amsbsy,float,wasysym,setspace,bm',
include=r'''
\newcommand{\mb}{\mathbf}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\newcommand{\bv}{\mathbf{v}}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\tp}{\tilde{p}}
\newcommand{\td}{\tilde{d}}
\newcommand{\te}{\tilde{e}}
\newcommand{\tw}{\tilde{w}}
\newcommand{\tf}{\tilde{f}}
\newcommand{\tc}{\tilde{c}}
\newcommand{\tv}{\tilde{v}_z}
\newcommand{\tu}{\tilde{u}}
\newcommand{\tS}{\tilde{S}}
\newcommand{\tk}{\tilde{\kappa}}
\newcommand{\tA}{\tilde{A}}
\newcommand{\wl}{w_{\lambda}}
\newcommand{\dl}{d_{\lambda}}
\newcommand{\tdl}{\tilde{d}_{\lambda}}
\newcommand{\tul}{\tilde{u}_{\lambda}}
\newcommand{\bR}{\mathbf{R}}
\newcommand{\cF}{{\cal F}}
\newtheorem{exmp}{Example}
\newtheorem{theorem}{Theorem}
''')

Paper('diff',
lclass='georeport',
options='notimes',
use='hyperref,natbib,graphicx,color,listings,amsmath,amsthm,amssymb,amsbsy,float,wasysym,setspace,bm',
include=r'''
\newcommand{\mb}{\mathbf}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\newcommand{\bv}{\mathbf{v}}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\tp}{\tilde{p}}
\newcommand{\td}{\tilde{d}}
\newcommand{\te}{\tilde{e}}
\newcommand{\tw}{\tilde{w}}
\newcommand{\tf}{\tilde{f}}
\newcommand{\tc}{\tilde{c}}
\newcommand{\tv}{\tilde{v}_z}
\newcommand{\tu}{\tilde{u}}
\newcommand{\tS}{\tilde{S}}
\newcommand{\tk}{\tilde{\kappa}}
\newcommand{\tA}{\tilde{A}}
\newcommand{\wl}{w_{\lambda}}
\newcommand{\dl}{d_{\lambda}}
\newcommand{\tdl}{\tilde{d}_{\lambda}}
\newcommand{\tul}{\tilde{u}_{\lambda}}
\newcommand{\bR}{\mathbf{R}}
\newcommand{\cF}{{\cal F}}
\newtheorem{exmp}{Example}
\newtheorem{theorem}{Theorem}
''')

End(
#lclass='segabs',
lclass='georeport',
#options='report',
#options='manuscript',
#options='paper',
use='amsmath,amssymb,amsthm,amscd,setspace,wasysym,graphicx,hyperref',

include=r'''
\newcommand{\mb}{\mathbf}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\newcommand{\bv}{\mathbf{v}}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\tp}{\tilde{p}}
\newcommand{\td}{\tilde{d}}
\newcommand{\te}{\tilde{e}}
\newcommand{\tw}{\tilde{w}}
\newcommand{\tf}{\tilde{f}}
\newcommand{\tc}{\tilde{c}}
\newcommand{\tv}{\tilde{v}_z}
\newcommand{\tu}{\tilde{u}}
\newcommand{\tS}{\tilde{S}}
\newcommand{\tk}{\tilde{\kappa}}
\newcommand{\tA}{\tilde{A}}
\newcommand{\wl}{w_{\lambda}}
\newcommand{\dl}{d_{\lambda}}
\newcommand{\tdl}{\tilde{d}_{\lambda}}
\newcommand{\tul}{\tilde{u}_{\lambda}}
\newcommand{\bR}{\mathbf{R}}
\newcommand{\cF}{{\cal F}}
\newtheorem{exmp}{Example}
\newtheorem{theorem}{Theorem}
''',
color='ALL'
)





