/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/
//#include "GlobalDeclarations_b.c"
#include <stdio.h>
#include "adBuffer.h"

/*
  Differentiation of asg2d in reverse (adjoint) mode:
   gradient     of useful results: **v0 **v1 **p0 **p1
   with respect to varying inputs: **v0 **v1 **bulk **buoy **p0
                **p1
   RW status of diff variables: **v0:in-out **v1:in-out **bulk:out
                **buoy:out **p0:in-out **p1:in-out
   Plus diff mem management of: v0:in *v0:in v1:in *v1:in bulk:in
                *bulk:in buoy:in *buoy:in p0:in *p0:in p1:in *p1:in
                sdiv:in gradp:in *gradp:in

 signature for tapenade */
void asg2d_b(float **bulk, float **bulkb, float **buoy, float **buoyb, float *
        *p0, float **p0b, float **p1, float **p1b, float **v0, float **v0b, 
        float **v1, float **v1b, float **ep, float **epp, float **ev, float **
        evp, float *sdiv, float *sdivb, float **gradp, float **gradpb, int *
        gsc_p, int *gec_p, int *gsc_v0, int *gec_v0, int *gsc_v1, int *gec_v1,
        int *lbc, int *rbc, int maxoff, float **c, FILE *stream) {
    int i0, i1;
    int ioff;
    float tempb;
    float tempb0;
    float tempb1;
    float tempb2;
    float tmp;
    float tmpb;
    float tmp0;
    float tmpb0;
    float tmp1;
    float tmpb1;
    float tmp2;
    float tmpb2;
    float tempb3;
    float tempb4;
    float tempb5;
    float tempb6;
    float tempb7;
    float tempb8;
    float tmp3;
    float tmpb3;
    float tmp4;
    float tmpb4;
    float tmp5;
    float tmpb5;
    float tmp6;
    float tmpb6;
    int branch;
    for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            pushreal4(sdiv[i0]);
            sdiv[i0] = c[0][0]*(v0[i1][i0]-v0[i1][i0-1]) + c[1][0]*(v1[i1][i0]
                -v1[i1-1][i0]);
        }
        for (ioff = 1; ioff < maxoff; ++ioff)
            for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
                pushreal4(sdiv[i0]);
                sdiv[i0] = sdiv[i0] + (c[0][ioff]*(v0[i1][i0+ioff]-v0[i1][i0-
                    ioff-1]) + c[1][ioff]*(v1[i1+ioff][i0]-v1[i1-ioff-1][i0]))
                ;
            }
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            p0[i1][i0] = (p0[i1][i0]*ep[0][i0]-bulk[i1][i0]*sdiv[i0])*epp[0][
                i0];
            p1[i1][i0] = (p1[i1][i0]*ep[1][i1]-bulk[i1][i0]*sdiv[i0])*epp[1][
                i1];
        }
    }
    if (lbc[0]) {
        for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
            p0[i1][gsc_p[0] - 1] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                tmp = -p0[i1][gsc_p[0]+ioff-1];
                p0[i1][gsc_p[0] - ioff - 1] = tmp;
            }
        }
        pushcontrol1b(0);
    } else
        pushcontrol1b(1);
    if (rbc[0]) {
        for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
            p0[i1][gec_p[0] + 1] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                tmp0 = -p0[i1][gec_p[0]-ioff+1];
                p0[i1][gec_p[0] + ioff + 1] = tmp0;
            }
        }
        pushcontrol1b(0);
    } else
        pushcontrol1b(1);
    if (lbc[1]) {
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            p1[gsc_p[1] - 1][i0] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                tmp1 = -p1[gsc_p[1]+ioff-1][i0];
                p1[gsc_p[1] - ioff - 1][i0] = tmp1;
            }
        }
        pushcontrol1b(0);
    } else
        pushcontrol1b(1);
    if (rbc[1]) {
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            p1[gec_p[1] + 1][i0] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                tmp2 = -p1[gec_p[1]-ioff+1][i0];
                p1[gec_p[1] + ioff + 1][i0] = tmp2;
            }
        }
        pushcontrol1b(1);
    } else
        pushcontrol1b(0);
    for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1) {
        for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
            pushreal4(gradp[0][i0]);
            gradp[0][i0] = 0;
        }
        for (ioff = 0; ioff < maxoff; ++ioff)
            for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
                pushreal4(gradp[0][i0]);
                gradp[0][i0] = gradp[0][i0] + c[0][ioff]*(p0[i1][i0+ioff+1]-p0
                    [i1][i0-ioff]);
            }
    }
    for (i1 = gsc_v1[1]; i1 < gec_v1[1]+1; ++i1) {
        for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
            pushreal4(gradp[1][i0]);
            gradp[1][i0] = 0;
        }
        for (ioff = 0; ioff < maxoff; ++ioff)
            for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
                pushreal4(gradp[1][i0]);
                gradp[1][i0] = gradp[1][i0] + c[1][ioff]*(p1[i1+ioff+1][i0]-p1
                    [i1-ioff][i0]);
            }
    }
    if (lbc[0])
        pushcontrol1b(0);
    else
        pushcontrol1b(1);
    if (rbc[0])
        pushcontrol1b(0);
    else
        pushcontrol1b(1);
    if (lbc[1])
        pushcontrol1b(0);
    else
        pushcontrol1b(1);
    if (rbc[1])
        for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0)
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb6 = v1b[gec_v1[1] + ioff][i0];
                v1b[gec_v1[1] + ioff][i0] = 0.0;
                v1b[gec_v1[1] - ioff + 1][i0] = v1b[gec_v1[1] - ioff + 1][i0] 
                    + tmpb6;
            }
    popcontrol1b(&branch);
    if (branch == 0)
        for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0)
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb5 = v1b[gsc_v1[1] - ioff][i0];
                v1b[gsc_v1[1] - ioff][i0] = 0.0;
                v1b[gsc_v1[1] + ioff - 1][i0] = v1b[gsc_v1[1] + ioff - 1][i0] 
                    + tmpb5;
            }
    popcontrol1b(&branch);
    if (branch == 0)
        for (i1 = gec_v0[1]; i1 > gsc_v0[1]-1; --i1)
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb4 = v0b[i1][gec_v0[0] + ioff];
                v0b[i1][gec_v0[0] + ioff] = 0.0;
                v0b[i1][gec_v0[0] - ioff + 1] = v0b[i1][gec_v0[0] - ioff + 1] 
                    + tmpb4;
            }
    popcontrol1b(&branch);
    if (branch == 0)
        for (i1 = gec_v0[1]; i1 > gsc_v0[1]-1; --i1)
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb3 = v0b[i1][gsc_v0[0] - ioff];
                v0b[i1][gsc_v0[0] - ioff] = 0.0;
                v0b[i1][gsc_v0[0] + ioff - 1] = v0b[i1][gsc_v0[0] + ioff - 1] 
                    + tmpb3;
            }
    **buoyb = 0.0;
    **gradpb = 0.0;
    for (i1 = gec_v1[1]; i1 > gsc_v1[1]-1; --i1) {
        for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
            tempb7 = evp[1][i1]*v1b[i1][i0];
            tempb8 = -(0.5*gradp[1][i0]*tempb7);
            buoyb[i1][i0] = buoyb[i1][i0] + tempb8;
            buoyb[i1 + 1][i0] = buoyb[i1 + 1][i0] + tempb8;
            gradpb[1][i0] = gradpb[1][i0] - 0.5*(buoy[i1][i0]+buoy[i1+1][i0])*
                tempb7;
            v1b[i1][i0] = ev[1][i1]*tempb7;
        }
        for (ioff = maxoff-1; ioff > -1; --ioff)
            for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
                popreal4(&gradp[1][i0]);
                tempb6 = c[1][ioff]*gradpb[1][i0];
                p1b[i1 + ioff + 1][i0] = p1b[i1 + ioff + 1][i0] + tempb6;
                p1b[i1 - ioff][i0] = p1b[i1 - ioff][i0] - tempb6;
            }
        for (i0 = gec_v1[0]; i0 > gsc_v1[0]-1; --i0) {
            popreal4(&gradp[1][i0]);
            gradpb[1][i0] = 0.0;
        }
    }
    for (i1 = gec_v0[1]; i1 > gsc_v0[1]-1; --i1) {
        for (i0 = gec_v0[0]; i0 > gsc_v0[0]-1; --i0) {
            tempb4 = evp[0][i0]*v0b[i1][i0];
            tempb5 = -(0.5*gradp[0][i0]*tempb4);
            buoyb[i1][i0] = buoyb[i1][i0] + tempb5;
            buoyb[i1][i0 + 1] = buoyb[i1][i0 + 1] + tempb5;
            gradpb[0][i0] = gradpb[0][i0] - 0.5*(buoy[i1][i0]+buoy[i1][i0+1])*
                tempb4;
            v0b[i1][i0] = ev[0][i0]*tempb4;
        }
        for (ioff = maxoff-1; ioff > -1; --ioff)
            for (i0 = gec_v0[0]; i0 > gsc_v0[0]-1; --i0) {
                popreal4(&gradp[0][i0]);
                tempb3 = c[0][ioff]*gradpb[0][i0];
                p0b[i1][i0 + ioff + 1] = p0b[i1][i0 + ioff + 1] + tempb3;
                p0b[i1][i0 - ioff] = p0b[i1][i0 - ioff] - tempb3;
            }
        for (i0 = gec_v0[0]; i0 > gsc_v0[0]-1; --i0) {
            popreal4(&gradp[0][i0]);
            gradpb[0][i0] = 0.0;
        }
    }
    popcontrol1b(&branch);
    if (branch != 0)
        for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb2 = p1b[gec_p[1] + ioff + 1][i0];
                p1b[gec_p[1] + ioff + 1][i0] = 0.0;
                p1b[gec_p[1] - ioff + 1][i0] = p1b[gec_p[1] - ioff + 1][i0] - 
                    tmpb2;
            }
            p1b[gec_p[1] + 1][i0] = 0.0;
        }
    popcontrol1b(&branch);
    if (branch == 0)
        for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb1 = p1b[gsc_p[1] - ioff - 1][i0];
                p1b[gsc_p[1] - ioff - 1][i0] = 0.0;
                p1b[gsc_p[1] + ioff - 1][i0] = p1b[gsc_p[1] + ioff - 1][i0] - 
                    tmpb1;
            }
            p1b[gsc_p[1] - 1][i0] = 0.0;
        }
    popcontrol1b(&branch);
    if (branch == 0)
        for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb0 = p0b[i1][gec_p[0] + ioff + 1];
                p0b[i1][gec_p[0] + ioff + 1] = 0.0;
                p0b[i1][gec_p[0] - ioff + 1] = p0b[i1][gec_p[0] - ioff + 1] - 
                    tmpb0;
            }
            p0b[i1][gec_p[0] + 1] = 0.0;
        }
    popcontrol1b(&branch);
    if (branch == 0)
        for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
            for (ioff = maxoff-1; ioff > 0; --ioff) {
                tmpb = p0b[i1][gsc_p[0] - ioff - 1];
                p0b[i1][gsc_p[0] - ioff - 1] = 0.0;
                p0b[i1][gsc_p[0] + ioff - 1] = p0b[i1][gsc_p[0] + ioff - 1] - 
                    tmpb;
            }
            p0b[i1][gsc_p[0] - 1] = 0.0;
        }
    **bulkb = 0.0;
    *sdivb = 0.0;
    for (i1 = gec_p[1]; i1 > gsc_p[1]-1; --i1) {
        for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
            tempb1 = epp[1][i1]*p1b[i1][i0];
            bulkb[i1][i0] = bulkb[i1][i0] - sdiv[i0]*tempb1;
            sdivb[i0] = sdivb[i0] - bulk[i1][i0]*tempb1;
            p1b[i1][i0] = ep[1][i1]*tempb1;
            tempb2 = epp[0][i0]*p0b[i1][i0];
            bulkb[i1][i0] = bulkb[i1][i0] - sdiv[i0]*tempb2;
            sdivb[i0] = sdivb[i0] - bulk[i1][i0]*tempb2;
            p0b[i1][i0] = ep[0][i0]*tempb2;
        }
        for (ioff = maxoff-1; ioff > 0; --ioff)
            for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
                popreal4(&sdiv[i0]);
                tempb = c[0][ioff]*sdivb[i0];
                tempb0 = c[1][ioff]*sdivb[i0];
                v0b[i1][i0 + ioff] = v0b[i1][i0 + ioff] + tempb;
                v0b[i1][i0 - ioff - 1] = v0b[i1][i0 - ioff - 1] - tempb;
                v1b[i1 + ioff][i0] = v1b[i1 + ioff][i0] + tempb0;
                v1b[i1 - ioff - 1][i0] = v1b[i1 - ioff - 1][i0] - tempb0;
            }
        for (i0 = gec_p[0]; i0 > gsc_p[0]-1; --i0) {
            popreal4(&sdiv[i0]);
            v0b[i1][i0] = v0b[i1][i0] + c[0][0]*sdivb[i0];
            v0b[i1][i0 - 1] = v0b[i1][i0 - 1] - c[0][0]*sdivb[i0];
            v1b[i1][i0] = v1b[i1][i0] + c[1][0]*sdivb[i0];
            v1b[i1 - 1][i0] = v1b[i1 - 1][i0] - c[1][0]*sdivb[i0];
            sdivb[i0] = 0.0;
        }
    }
}
