/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/
#include <stdio.h>

/*
  Differentiation of asg2d in forward (tangent) mode:
   variations   of useful results: **v0 **v1 **p0 **p1
   with respect to varying inputs: **v0 **v1 **bulk **buoy **p0
                **p1
   RW status of diff variables: **v0:in-out **v1:in-out **bulk:in
                **buoy:in **p0:in-out **p1:in-out
   Plus diff mem management of: v0:in *v0:in v1:in *v1:in bulk:in
                *bulk:in buoy:in *buoy:in p0:in *p0:in p1:in *p1:in
                sdiv:in gradp:in *gradp:in

 signature for tapenade */
void asg2d_d(float **bulk, float **bulkd, float **buoy, float **buoyd, float *
        *p0, float **p0d, float **p1, float **p1d, float **v0, float **v0d, 
        float **v1, float **v1d, float **ep, float **epp, float **ev, float **
        evp, float *sdiv, float *sdivd, float **gradp, float **gradpd, int *
        gsc_p, int *gec_p, int *gsc_v0, int *gec_v0, int *gsc_v1, int *gec_v1,
        int *lbc, int *rbc, int maxoff, float **c, FILE *stream) {
    int i0, i1;
    int ioff;
    *sdivd = 0.0;
    for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            sdivd[i0] = c[0][0]*(v0d[i1][i0]-v0d[i1][i0-1]) + c[1][0]*(v1d[i1]
                [i0]-v1d[i1-1][i0]);
            sdiv[i0] = c[0][0]*(v0[i1][i0]-v0[i1][i0-1]) + c[1][0]*(v1[i1][i0]
                -v1[i1-1][i0]);
        }
        for (ioff = 1; ioff < maxoff; ++ioff)
            for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
                sdivd[i0] = sdivd[i0] + c[0][ioff]*(v0d[i1][i0+ioff]-v0d[i1][
                    i0-ioff-1]) + c[1][ioff]*(v1d[i1+ioff][i0]-v1d[i1-ioff-1][
                    i0]);
                sdiv[i0] += c[0][ioff]*(v0[i1][i0+ioff]-v0[i1][i0-ioff-1]) + c
                [1][ioff]*(v1[i1+ioff][i0]-v1[i1-ioff-1][i0]);
            }
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            p0d[i1][i0] = epp[0][i0]*(ep[0][i0]*p0d[i1][i0]-bulkd[i1][i0]*sdiv
                [i0]-bulk[i1][i0]*sdivd[i0]);
            p0[i1][i0] = (p0[i1][i0]*ep[0][i0]-bulk[i1][i0]*sdiv[i0])*epp[0][
                i0];
            p1d[i1][i0] = epp[1][i1]*(ep[1][i1]*p1d[i1][i0]-bulkd[i1][i0]*sdiv
                [i0]-bulk[i1][i0]*sdivd[i0]);
            p1[i1][i0] = (p1[i1][i0]*ep[1][i1]-bulk[i1][i0]*sdiv[i0])*epp[1][
                i1];
        }
    }
    if (lbc[0])
        for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
            p0d[i1][gsc_p[0] - 1] = 0.0;
            p0[i1][gsc_p[0] - 1] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                p0d[i1][gsc_p[0] - ioff - 1] = -p0d[i1][gsc_p[0]+ioff-1];
                p0[i1][gsc_p[0] - ioff - 1] = -p0[i1][gsc_p[0]+ioff-1];
            }
        }
    if (rbc[0])
        for (i1 = gsc_p[1]; i1 < gec_p[1]+1; ++i1) {
            p0d[i1][gec_p[0] + 1] = 0.0;
            p0[i1][gec_p[0] + 1] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                p0d[i1][gec_p[0] + ioff + 1] = -p0d[i1][gec_p[0]-ioff+1];
                p0[i1][gec_p[0] + ioff + 1] = -p0[i1][gec_p[0]-ioff+1];
            }
        }
    if (lbc[1])
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            p1d[gsc_p[1] - 1][i0] = 0.0;
            p1[gsc_p[1] - 1][i0] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                p1d[gsc_p[1] - ioff - 1][i0] = -p1d[gsc_p[1]+ioff-1][i0];
                p1[gsc_p[1] - ioff - 1][i0] = -p1[gsc_p[1]+ioff-1][i0];
            }
        }
    if (rbc[1]) {
        for (i0 = gsc_p[0]; i0 < gec_p[0]+1; ++i0) {
            p1d[gec_p[1] + 1][i0] = 0.0;
            p1[gec_p[1] + 1][i0] = 0.0f;
            for (ioff = 1; ioff < maxoff; ++ioff) {
                p1d[gec_p[1] + ioff + 1][i0] = -p1d[gec_p[1]-ioff+1][i0];
                p1[gec_p[1] + ioff + 1][i0] = -p1[gec_p[1]-ioff+1][i0];
            }
        }
        **gradpd = 0.0;
    } else
        **gradpd = 0.0;
    for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1) {
        for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
            gradpd[0][i0] = 0.0;
            gradp[0][i0] = 0;
        }
        for (ioff = 0; ioff < maxoff; ++ioff)
            for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
                gradpd[0][i0] = gradpd[0][i0] + c[0][ioff]*(p0d[i1][i0+ioff+1]
                    -p0d[i1][i0-ioff]);
                gradp[0][i0] += c[0][ioff]*(p0[i1][i0+ioff+1]-p0[i1][i0-ioff])
                ;
            }
        for (i0 = gsc_v0[0]; i0 < gec_v0[0]+1; ++i0) {
            v0d[i1][i0] = evp[0][i0]*(ev[0][i0]*v0d[i1][i0]-0.5*((buoyd[i1][i0
                ]+buoyd[i1][i0+1])*gradp[0][i0]+(buoy[i1][i0]+buoy[i1][i0+1])*
                gradpd[0][i0]));
            v0[i1][i0] = evp[0][i0]*(v0[i1][i0]*ev[0][i0]-0.5*(buoy[i1][i0]+
                buoy[i1][i0+1])*gradp[0][i0]);
        }
    }
    for (i1 = gsc_v1[1]; i1 < gec_v1[1]+1; ++i1) {
        for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
            gradpd[1][i0] = 0.0;
            gradp[1][i0] = 0;
        }
        for (ioff = 0; ioff < maxoff; ++ioff)
            for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
                gradpd[1][i0] = gradpd[1][i0] + c[1][ioff]*(p1d[i1+ioff+1][i0]
                    -p1d[i1-ioff][i0]);
                gradp[1][i0] += c[1][ioff]*(p1[i1+ioff+1][i0]-p1[i1-ioff][i0])
                ;
            }
        for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0) {
            v1d[i1][i0] = evp[1][i1]*(ev[1][i1]*v1d[i1][i0]-0.5*((buoyd[i1][i0
                ]+buoyd[i1+1][i0])*gradp[1][i0]+(buoy[i1][i0]+buoy[i1+1][i0])*
                gradpd[1][i0]));
            v1[i1][i0] = evp[1][i1]*(v1[i1][i0]*ev[1][i1]-0.5*(buoy[i1][i0]+
                buoy[i1+1][i0])*gradp[1][i0]);
        }
    }
    if (lbc[0])
        for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1)
            for (ioff = 1; ioff < maxoff; ++ioff) {
                v0d[i1][gsc_v0[0] - ioff] = v0d[i1][gsc_v0[0] + ioff - 1];
                v0[i1][gsc_v0[0] - ioff] = v0[i1][gsc_v0[0] + ioff - 1];
            }
    if (rbc[0])
        for (i1 = gsc_v0[1]; i1 < gec_v0[1]+1; ++i1)
            for (ioff = 1; ioff < maxoff; ++ioff) {
                v0d[i1][gec_v0[0] + ioff] = v0d[i1][gec_v0[0] - ioff + 1];
                v0[i1][gec_v0[0] + ioff] = v0[i1][gec_v0[0] - ioff + 1];
            }
    if (lbc[1])
        for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0)
            for (ioff = 1; ioff < maxoff; ++ioff) {
                v1d[gsc_v1[1] - ioff][i0] = v1d[gsc_v1[1] + ioff - 1][i0];
                v1[gsc_v1[1] - ioff][i0] = v1[gsc_v1[1] + ioff - 1][i0];
            }
    if (rbc[1])
        for (i0 = gsc_v1[0]; i0 < gec_v1[0]+1; ++i0)
            for (ioff = 1; ioff < maxoff; ++ioff) {
                v1d[gec_v1[1] + ioff][i0] = v1d[gec_v1[1] - ioff + 1][i0];
                v1[gec_v1[1] + ioff][i0] = v1[gec_v1[1] - ioff + 1][i0];
            }
}
