"/******************************************************************************",
" * Acoustic variable density staggered grid linearized forward and adjoint    * ",
" * modeling and approximate inversion in 2D (3D coming soon!)                 * ", 
" *                                                                            * ",
" * Algorithm: Jie Hou and William W. Symes, papers in Geophysics 2015-2017    * ",  
" * Code: Igor Terentyev, Tanya Vdovina, Xin Wang, Rami Nammour, Dong Sun,     *",
" *   Mario J. Bencomo, Muhong Zhou, Yin Huang, and William W. Symes           *",
" ******************************************************************************/",
" ",
