" ------------------------------ asg params-------------------------------------",
  " Model Parameters:",
  " ",
  "        bulkmod = <path>      input bulk modulus reference file, ",
  "                              determines simulation spatial grid,",
  "       buoyancy = <path>      input buoyancy (1/density) reference file, ",
  "                              must us same spatial grid as bulkmod",
  " Source Parameters:",
  "       source_p = \"\"        RHS data for p update",
  "      source_v0 = \"\"        RHS data for v0 update",
  "      source_v1 = \"\"        RHS data for v1 update",
  "      source_v2 = \"\"        RHS data for v2 update",
  " Note: at least one source file must be specified",
  " ",
  " Output Parameters:",
  "        data_p  = \"\"        pressure",
  "        data_v0 = \"\"        z component of velocity",
  "        data_v1 = \"\"        x component of velocity",
  "        data_v2 = \"\"        y component of velocity",
    " Note: at least one output file must be specified",
  " ",
" ------------------------------ asg params-------------------------------------",
